if(typeof Math.imul == "undefined" || (Math.imul(0xffffffff,5) == 0)) {
    Math.imul = function (a, b) {
        var ah  = (a >>> 16) & 0xffff;
        var al = a & 0xffff;
        var bh  = (b >>> 16) & 0xffff;
        var bl = b & 0xffff;
        // the shift by 0 fixes the sign on the high part
        // the final |0 converts the unsigned value into a signed value
        return ((al * bl) + (((ah * bl + al * bh) << 16) >>> 0)|0);
    }
}


var f,aa=this;
function q(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b}var ba="closure_uid_"+(1E9*Math.random()>>>0),da=0;function ea(a){return Array.prototype.join.call(arguments,"")}function ga(a,b){return a<b?-1:a>b?1:0};function ia(a,b){for(var c in a)b.call(void 0,a[c],c,a)};function ja(a,b){null!=a&&this.append.apply(this,arguments)}f=ja.prototype;f.ya="";f.set=function(a){this.ya=""+a};f.append=function(a,b,c){this.ya+=a;if(null!=b)for(var d=1;d<arguments.length;d++)this.ya+=arguments[d];return this};f.clear=function(){this.ya=""};f.toString=function(){return this.ya};if("undefined"===typeof ka)var ka=function(){throw Error("No *print-fn* fn set for evaluation environment");};var na=!0,pa=null;if("undefined"===typeof qa)var qa=null;function ra(){return new u(null,5,[ua,!0,va,!0,wa,!1,ya,!1,za,null],null)}function v(a){return null!=a&&!1!==a}function Aa(a){return a instanceof Array}function z(a,b){return a[q(null==b?null:b)]?!0:a._?!0:!1}
function B(a,b){var c=null==b?null:b.constructor,c=v(v(c)?c.Cb:c)?c.Bb:q(b);return Error(["No protocol method ",a," defined for type ",c,": ",b].join(""))}function Ba(a){var b=a.Bb;return v(b)?b:""+C(a)}var Ca="undefined"!==typeof Symbol&&"function"===q(Symbol)?Symbol.iterator:"@@iterator";function E(a){for(var b=a.length,c=Array(b),d=0;;)if(d<b)c[d]=a[d],d+=1;else break;return c}
function Ea(){switch(arguments.length){case 1:return Fa(arguments[0]);case 2:return Fa(arguments[1]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}function Ha(a){return Fa(a)}function Fa(a){function b(a,b){a.push(b);return a}var c=[];return Ia?Ia(b,c,a):Ja.call(null,b,c,a)}
var Ka={},La={},Ma=function Ma(b){if(b?b.O:b)return b.O(b);var c;c=Ma[q(null==b?null:b)];if(!c&&(c=Ma._,!c))throw B("ICounted.-count",b);return c.call(null,b)},Na=function Na(b,c){if(b?b.G:b)return b.G(b,c);var d;d=Na[q(null==b?null:b)];if(!d&&(d=Na._,!d))throw B("ICollection.-conj",b);return d.call(null,b,c)},Qa={},F=function F(){switch(arguments.length){case 2:return F.a(arguments[0],arguments[1]);case 3:return F.e(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),
C(arguments.length)].join(""));}};F.a=function(a,b){if(a?a.J:a)return a.J(a,b);var c;c=F[q(null==a?null:a)];if(!c&&(c=F._,!c))throw B("IIndexed.-nth",a);return c.call(null,a,b)};F.e=function(a,b,c){if(a?a.T:a)return a.T(a,b,c);var d;d=F[q(null==a?null:a)];if(!d&&(d=F._,!d))throw B("IIndexed.-nth",a);return d.call(null,a,b,c)};F.t=3;
var Ra={},G=function G(b){if(b?b.M:b)return b.M(b);var c;c=G[q(null==b?null:b)];if(!c&&(c=G._,!c))throw B("ISeq.-first",b);return c.call(null,b)},H=function H(b){if(b?b.R:b)return b.R(b);var c;c=H[q(null==b?null:b)];if(!c&&(c=H._,!c))throw B("ISeq.-rest",b);return c.call(null,b)},Sa={},Ta={},I=function I(){switch(arguments.length){case 2:return I.a(arguments[0],arguments[1]);case 3:return I.e(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));
}};I.a=function(a,b){if(a?a.u:a)return a.u(a,b);var c;c=I[q(null==a?null:a)];if(!c&&(c=I._,!c))throw B("ILookup.-lookup",a);return c.call(null,a,b)};I.e=function(a,b,c){if(a?a.B:a)return a.B(a,b,c);var d;d=I[q(null==a?null:a)];if(!d&&(d=I._,!d))throw B("ILookup.-lookup",a);return d.call(null,a,b,c)};I.t=3;
var Ua=function Ua(b,c,d){if(b?b.aa:b)return b.aa(b,c,d);var e;e=Ua[q(null==b?null:b)];if(!e&&(e=Ua._,!e))throw B("IAssociative.-assoc",b);return e.call(null,b,c,d)},Va={},Wa={},Xa=function Xa(b){if(b?b.ab:b)return b.ab();var c;c=Xa[q(null==b?null:b)];if(!c&&(c=Xa._,!c))throw B("IMapEntry.-key",b);return c.call(null,b)},Za=function Za(b){if(b?b.bb:b)return b.bb();var c;c=Za[q(null==b?null:b)];if(!c&&(c=Za._,!c))throw B("IMapEntry.-val",b);return c.call(null,b)},$a={},ab=function ab(b,c,d){if(b?b.cb:
b)return b.cb(b,c,d);var e;e=ab[q(null==b?null:b)];if(!e&&(e=ab._,!e))throw B("IVector.-assoc-n",b);return e.call(null,b,c,d)},bb=function bb(b){if(b?b.nb:b)return b.state;var c;c=bb[q(null==b?null:b)];if(!c&&(c=bb._,!c))throw B("IDeref.-deref",b);return c.call(null,b)},cb={},db=function db(b){if(b?b.D:b)return b.D(b);var c;c=db[q(null==b?null:b)];if(!c&&(c=db._,!c))throw B("IMeta.-meta",b);return c.call(null,b)},eb={},gb=function gb(b,c){if(b?b.I:b)return b.I(b,c);var d;d=gb[q(null==b?null:b)];if(!d&&
(d=gb._,!d))throw B("IWithMeta.-with-meta",b);return d.call(null,b,c)},hb={},ib=function ib(){switch(arguments.length){case 2:return ib.a(arguments[0],arguments[1]);case 3:return ib.e(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}};ib.a=function(a,b){if(a?a.K:a)return a.K(a,b);var c;c=ib[q(null==a?null:a)];if(!c&&(c=ib._,!c))throw B("IReduce.-reduce",a);return c.call(null,a,b)};
ib.e=function(a,b,c){if(a?a.L:a)return a.L(a,b,c);var d;d=ib[q(null==a?null:a)];if(!d&&(d=ib._,!d))throw B("IReduce.-reduce",a);return d.call(null,a,b,c)};ib.t=3;
var jb=function jb(b,c){if(b?b.k:b)return b.k(b,c);var d;d=jb[q(null==b?null:b)];if(!d&&(d=jb._,!d))throw B("IEquiv.-equiv",b);return d.call(null,b,c)},kb=function kb(b){if(b?b.A:b)return b.A(b);var c;c=kb[q(null==b?null:b)];if(!c&&(c=kb._,!c))throw B("IHash.-hash",b);return c.call(null,b)},lb={},mb=function mb(b){if(b?b.v:b)return b.v(b);var c;c=mb[q(null==b?null:b)];if(!c&&(c=mb._,!c))throw B("ISeqable.-seq",b);return c.call(null,b)},nb={},ob={},J=function J(b,c){if(b?b.ib:b)return b.ib(0,c);var d;
d=J[q(null==b?null:b)];if(!d&&(d=J._,!d))throw B("IWriter.-write",b);return d.call(null,b,c)},pb={},rb=function rb(b,c,d){if(b?b.r:b)return b.r(b,c,d);var e;e=rb[q(null==b?null:b)];if(!e&&(e=rb._,!e))throw B("IPrintWithWriter.-pr-writer",b);return e.call(null,b,c,d)},sb=function sb(b,c,d){if(b?b.hb:b)return b.hb(0,c,d);var e;e=sb[q(null==b?null:b)];if(!e&&(e=sb._,!e))throw B("IWatchable.-notify-watches",b);return e.call(null,b,c,d)},tb=function tb(b){if(b?b.Ja:b)return b.Ja(b);var c;c=tb[q(null==
b?null:b)];if(!c&&(c=tb._,!c))throw B("IEditableCollection.-as-transient",b);return c.call(null,b)},ub=function ub(b,c){if(b?b.Ta:b)return b.Ta(b,c);var d;d=ub[q(null==b?null:b)];if(!d&&(d=ub._,!d))throw B("ITransientCollection.-conj!",b);return d.call(null,b,c)},vb=function vb(b){if(b?b.Ua:b)return b.Ua(b);var c;c=vb[q(null==b?null:b)];if(!c&&(c=vb._,!c))throw B("ITransientCollection.-persistent!",b);return c.call(null,b)},wb=function wb(b,c,d){if(b?b.Ka:b)return b.Ka(b,c,d);var e;e=wb[q(null==b?
null:b)];if(!e&&(e=wb._,!e))throw B("ITransientAssociative.-assoc!",b);return e.call(null,b,c,d)},xb=function xb(b,c,d){if(b?b.gb:b)return b.gb(0,c,d);var e;e=xb[q(null==b?null:b)];if(!e&&(e=xb._,!e))throw B("ITransientVector.-assoc-n!",b);return e.call(null,b,c,d)},yb=function yb(b){if(b?b.fb:b)return b.fb();var c;c=yb[q(null==b?null:b)];if(!c&&(c=yb._,!c))throw B("IChunk.-drop-first",b);return c.call(null,b)},zb=function zb(b){if(b?b.Za:b)return b.Za(b);var c;c=zb[q(null==b?null:b)];if(!c&&(c=zb._,
!c))throw B("IChunkedSeq.-chunked-first",b);return c.call(null,b)},Ab=function Ab(b){if(b?b.$a:b)return b.$a(b);var c;c=Ab[q(null==b?null:b)];if(!c&&(c=Ab._,!c))throw B("IChunkedSeq.-chunked-rest",b);return c.call(null,b)},Bb=function Bb(b){if(b?b.Ya:b)return b.Ya(b);var c;c=Bb[q(null==b?null:b)];if(!c&&(c=Bb._,!c))throw B("IChunkedNext.-chunked-next",b);return c.call(null,b)},Cb=function Cb(b,c){if(b?b.wb:b)return b.wb(b,c);var d;d=Cb[q(null==b?null:b)];if(!d&&(d=Cb._,!d))throw B("IReset.-reset!",
b);return d.call(null,b,c)},Db=function Db(){switch(arguments.length){case 2:return Db.a(arguments[0],arguments[1]);case 3:return Db.e(arguments[0],arguments[1],arguments[2]);case 4:return Db.p(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return Db.w(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}};
Db.a=function(a,b){if(a?a.xb:a)return a.xb(a,b);var c;c=Db[q(null==a?null:a)];if(!c&&(c=Db._,!c))throw B("ISwap.-swap!",a);return c.call(null,a,b)};Db.e=function(a,b,c){if(a?a.yb:a)return a.yb(a,b,c);var d;d=Db[q(null==a?null:a)];if(!d&&(d=Db._,!d))throw B("ISwap.-swap!",a);return d.call(null,a,b,c)};Db.p=function(a,b,c,d){if(a?a.zb:a)return a.zb(a,b,c,d);var e;e=Db[q(null==a?null:a)];if(!e&&(e=Db._,!e))throw B("ISwap.-swap!",a);return e.call(null,a,b,c,d)};
Db.w=function(a,b,c,d,e){if(a?a.Ab:a)return a.Ab(a,b,c,d,e);var g;g=Db[q(null==a?null:a)];if(!g&&(g=Db._,!g))throw B("ISwap.-swap!",a);return g.call(null,a,b,c,d,e)};Db.t=5;var Fb=function Fb(b){if(b?b.Qa:b)return b.Qa(b);var c;c=Fb[q(null==b?null:b)];if(!c&&(c=Fb._,!c))throw B("IIterable.-iterator",b);return c.call(null,b)};function Gb(a){this.Db=a;this.f=1073741824;this.m=0}Gb.prototype.ib=function(a,b){return this.Db.append(b)};
function Hb(a){var b=new ja;a.r(null,new Gb(b),ra());return""+C(b)}var Ib="undefined"!==typeof Math.imul&&0!==(Math.imul.a?Math.imul.a(4294967295,5):Math.imul.call(null,4294967295,5))?function(a,b){return Math.imul.a?Math.imul.a(a,b):Math.imul.call(null,a,b)}:function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0};function Jb(a){a=Ib(a|0,-862048943);return Ib(a<<15|a>>>-15,461845907)}
function Kb(a,b){var c=(a|0)^(b|0);return Ib(c<<13|c>>>-13,5)+-430675100|0}function Lb(a,b){var c=(a|0)^b,c=Ib(c^c>>>16,-2048144789),c=Ib(c^c>>>13,-1028477387);return c^c>>>16}function Mb(a){var b;a:{b=1;for(var c=0;;)if(b<a.length){var d=b+2,c=Kb(c,Jb(a.charCodeAt(b-1)|a.charCodeAt(b)<<16));b=d}else{b=c;break a}}b=1===(a.length&1)?b^Jb(a.charCodeAt(a.length-1)):b;return Lb(b,Ib(2,a.length))}var Nb={},Ob=0;
function Qb(a){255<Ob&&(Nb={},Ob=0);var b=Nb[a];if("number"!==typeof b){a:if(null!=a)if(b=a.length,0<b)for(var c=0,d=0;;)if(c<b)var e=c+1,d=Ib(31,d)+a.charCodeAt(c),c=e;else{b=d;break a}else b=0;else b=0;Nb[a]=b;Ob+=1}return a=b}
function Rb(a){a&&(a.f&4194304||a.Hb)?a=a.A(null):"number"===typeof a?a=(Math.floor.d?Math.floor.d(a):Math.floor.call(null,a))%2147483647:!0===a?a=1:!1===a?a=0:"string"===typeof a?(a=Qb(a),0!==a&&(a=Jb(a),a=Kb(0,a),a=Lb(a,4))):a=a instanceof Date?a.valueOf():null==a?0:kb(a);return a}function Sb(a,b){return a^b+2654435769+(a<<6)+(a>>2)}function Tb(a,b,c,d,e){this.Oa=a;this.name=b;this.xa=c;this.Ba=d;this.S=e;this.f=2154168321;this.m=4096}f=Tb.prototype;f.toString=function(){return this.xa};
f.equiv=function(a){return this.k(null,a)};f.k=function(a,b){return b instanceof Tb?this.xa===b.xa:!1};f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return I.e(c,this,null);case 3:return I.e(c,this,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return I.e(c,this,null)};a.e=function(a,c,d){return I.e(c,this,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.d=function(a){return I.e(a,this,null)};
f.a=function(a,b){return I.e(a,this,b)};f.D=function(){return this.S};f.I=function(a,b){return new Tb(this.Oa,this.name,this.xa,this.Ba,b)};f.A=function(){var a=this.Ba;return null!=a?a:this.Ba=a=Sb(Mb(this.name),Qb(this.Oa))};f.r=function(a,b){return J(b,this.xa)};function L(a){if(null==a)return null;if(a&&(a.f&8388608||a.Jb))return a.v(null);if(Aa(a)||"string"===typeof a)return 0===a.length?null:new M(a,0);if(z(lb,a))return mb(a);throw Error([C(a),C(" is not ISeqable")].join(""));}
function N(a){if(null==a)return null;if(a&&(a.f&64||a.Sa))return a.M(null);a=L(a);return null==a?null:G(a)}function Ub(a){return null!=a?a&&(a.f&64||a.Sa)?a.R(null):(a=L(a))?H(a):Vb:Vb}function O(a){return null==a?null:a&&(a.f&128||a.Ra)?a.Q(null):L(Ub(a))}var P=function P(){switch(arguments.length){case 1:return P.d(arguments[0]);case 2:return P.a(arguments[0],arguments[1]);default:return P.i(arguments[0],arguments[1],new M(Array.prototype.slice.call(arguments,2),0))}};P.d=function(){return!0};
P.a=function(a,b){return null==a?null==b:a===b||jb(a,b)};P.i=function(a,b,c){for(;;)if(P.a(a,b))if(O(c))a=b,b=N(c),c=O(c);else return P.a(b,N(c));else return!1};P.s=function(a){var b=N(a),c=O(a);a=N(c);c=O(c);return P.i(b,a,c)};P.t=2;function Wb(a){this.n=a}Wb.prototype.next=function(){if(null!=this.n){var a=N(this.n);this.n=O(this.n);return{value:a,done:!1}}return{value:null,done:!0}};function Xb(a){return new Wb(L(a))}function Yb(a,b){var c=Jb(a),c=Kb(0,c);return Lb(c,b)}
function Zb(a){var b=0,c=1;for(a=L(a);;)if(null!=a)b+=1,c=Ib(31,c)+Rb(N(a))|0,a=O(a);else return Yb(c,b)}var $b=Yb(1,0);function ac(a){var b=0,c=0;for(a=L(a);;)if(null!=a)b+=1,c=c+Rb(N(a))|0,a=O(a);else return Yb(c,b)}var bc=Yb(0,0);La["null"]=!0;Ma["null"]=function(){return 0};Date.prototype.k=function(a,b){return b instanceof Date&&this.valueOf()===b.valueOf()};jb.number=function(a,b){return a===b};Ka["function"]=!0;cb["function"]=!0;db["function"]=function(){return null};
kb._=function(a){return a[ba]||(a[ba]=++da)};function cc(a){return a+1}function dc(a){return bb(a)}function ec(a,b){var c=Ma(a);if(0===c)return b.q?b.q():b.call(null);for(var d=F.a(a,0),e=1;;)if(e<c)var g=F.a(a,e),d=b.a?b.a(d,g):b.call(null,d,g),e=e+1;else return d}function fc(a,b,c){var d=Ma(a),e=c;for(c=0;;)if(c<d){var g=F.a(a,c),e=b.a?b.a(e,g):b.call(null,e,g);c+=1}else return e}
function gc(a,b){var c=a.length;if(0===a.length)return b.q?b.q():b.call(null);for(var d=a[0],e=1;;)if(e<c)var g=a[e],d=b.a?b.a(d,g):b.call(null,d,g),e=e+1;else return d}function hc(a,b,c){var d=a.length,e=c;for(c=0;;)if(c<d){var g=a[c],e=b.a?b.a(e,g):b.call(null,e,g);c+=1}else return e}function ic(a,b,c,d){for(var e=a.length;;)if(d<e){var g=a[d];c=b.a?b.a(c,g):b.call(null,c,g);d+=1}else return c}function jc(a){return a?a.f&2||a.mb?!0:a.f?!1:z(La,a):z(La,a)}function kc(a,b){this.b=a;this.h=b}
kc.prototype.eb=function(){return this.h<this.b.length};kc.prototype.next=function(){var a=this.b[this.h];this.h+=1;return a};function M(a,b){this.b=a;this.h=b;this.f=166199550;this.m=8192}f=M.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.J=function(a,b){var c=b+this.h;return c<this.b.length?this.b[c]:null};f.T=function(a,b,c){a=b+this.h;return a<this.b.length?this.b[a]:c};f.Qa=function(){return new kc(this.b,this.h)};
f.Q=function(){return this.h+1<this.b.length?new M(this.b,this.h+1):null};f.O=function(){return this.b.length-this.h};f.A=function(){return Zb(this)};f.k=function(a,b){return lc.a?lc.a(this,b):lc.call(null,this,b)};f.K=function(a,b){return ic(this.b,b,this.b[this.h],this.h+1)};f.L=function(a,b,c){return ic(this.b,b,c,this.h)};f.M=function(){return this.b[this.h]};f.R=function(){return this.h+1<this.b.length?new M(this.b,this.h+1):Vb};f.v=function(){return this};
f.G=function(a,b){return Q.a?Q.a(b,this):Q.call(null,b,this)};M.prototype[Ca]=function(){return Xb(this)};function mc(a,b){return b<a.length?new M(a,b):null}function nc(){switch(arguments.length){case 1:return mc(arguments[0],0);case 2:return mc(arguments[0],arguments[1]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}jb._=function(a,b){return a===b};
var oc=function oc(){switch(arguments.length){case 0:return oc.q();case 1:return oc.d(arguments[0]);case 2:return oc.a(arguments[0],arguments[1]);default:return oc.i(arguments[0],arguments[1],new M(Array.prototype.slice.call(arguments,2),0))}};oc.q=function(){return pc};oc.d=function(a){return a};oc.a=function(a,b){return null!=a?Na(a,b):Na(Vb,b)};oc.i=function(a,b,c){for(;;)if(v(c))a=oc.a(a,b),b=N(c),c=O(c);else return oc.a(a,b)};oc.s=function(a){var b=N(a),c=O(a);a=N(c);c=O(c);return oc.i(b,a,c)};
oc.t=2;function rc(a){if(null!=a)if(a&&(a.f&2||a.mb))a=a.O(null);else if(Aa(a))a=a.length;else if("string"===typeof a)a=a.length;else if(z(La,a))a=Ma(a);else a:{a=L(a);for(var b=0;;){if(jc(a)){a=b+Ma(a);break a}a=O(a);b+=1}}else a=0;return a}function sc(a,b){for(var c=null;;){if(null==a)return c;if(0===b)return L(a)?N(a):c;var d=a;if(d?d.f&16||d.pb||(d.f?0:z(Qa,d)):z(Qa,d))return F.e(a,b,c);if(L(a)){var d=O(a),e=b-1;a=d;b=e}else return c}}
function R(a,b){if("number"!==typeof b)throw Error("index argument to nth must be a number.");if(null==a)return null;if(a&&(a.f&16||a.pb))return a.T(null,b,null);if(Aa(a)||"string"===typeof a)return b<a.length?a[b]:null;if(z(Qa,a))return F.a(a,b);if(a?a.f&64||a.Sa||(a.f?0:z(Ra,a)):z(Ra,a))return sc(a,b);throw Error([C("nth not supported on this type "),C(Ba(null==a?null:a.constructor))].join(""));}
function S(a,b){return null==a?null:a&&(a.f&256||a.qb)?a.u(null,b):Aa(a)?b<a.length?a[b]:null:"string"===typeof a?b<a.length?a[b]:null:z(Ta,a)?I.a(a,b):null}function tc(a,b,c){return null!=a?a&&(a.f&256||a.qb)?a.B(null,b,c):Aa(a)?b<a.length?a[b]:c:"string"===typeof a?b<a.length?a[b]:c:z(Ta,a)?I.e(a,b,c):c:c}
var uc=function uc(){switch(arguments.length){case 3:return uc.e(arguments[0],arguments[1],arguments[2]);default:return uc.i(arguments[0],arguments[1],arguments[2],new M(Array.prototype.slice.call(arguments,3),0))}};uc.e=function(a,b,c){if(null!=a)a=Ua(a,b,c);else a:{a=[b];c=[c];b=a.length;var d=0,e;for(e=tb(vc);;)if(d<b){var g=d+1;e=e.Ka(null,a[d],c[d]);d=g}else{a=vb(e);break a}}return a};uc.i=function(a,b,c,d){for(;;)if(a=uc.e(a,b,c),v(d))b=N(d),c=N(O(d)),d=O(O(d));else return a};
uc.s=function(a){var b=N(a),c=O(a);a=N(c);var d=O(c),c=N(d),d=O(d);return uc.i(b,a,c,d)};uc.t=3;function wc(a){var b="function"==q(a);return v(b)?b:a?v(v(null)?null:a.lb)?!0:a.Ob?!1:z(Ka,a):z(Ka,a)}function xc(a,b){this.c=a;this.l=b;this.f=393217;this.m=0}f=xc.prototype;f.D=function(){return this.l};f.I=function(a,b){return new xc(this.c,b)};f.lb=!0;
f.call=function(){function a(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,y,K,T,ma){a=this.c;return yc.Pa?yc.Pa(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,y,K,T,ma):yc.call(null,a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,y,K,T,ma)}function b(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,y,K,T){a=this;return a.c.na?a.c.na(b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,y,K,T):a.c.call(null,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,y,K,T)}function c(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,y,K){a=this;return a.c.ma?a.c.ma(b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,y,
K):a.c.call(null,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,y,K)}function d(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,y){a=this;return a.c.la?a.c.la(b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,y):a.c.call(null,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,y)}function e(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D){a=this;return a.c.ka?a.c.ka(b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D):a.c.call(null,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D)}function g(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A){a=this;return a.c.ja?a.c.ja(b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A):a.c.call(null,
b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A)}function h(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x){a=this;return a.c.ia?a.c.ia(b,c,d,e,g,h,k,l,m,n,p,r,t,w,x):a.c.call(null,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x)}function k(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w){a=this;return a.c.ha?a.c.ha(b,c,d,e,g,h,k,l,m,n,p,r,t,w):a.c.call(null,b,c,d,e,g,h,k,l,m,n,p,r,t,w)}function l(a,b,c,d,e,g,h,k,l,m,n,p,r,t){a=this;return a.c.ga?a.c.ga(b,c,d,e,g,h,k,l,m,n,p,r,t):a.c.call(null,b,c,d,e,g,h,k,l,m,n,p,r,t)}function m(a,b,c,d,e,g,h,k,l,m,n,p,r){a=this;
return a.c.fa?a.c.fa(b,c,d,e,g,h,k,l,m,n,p,r):a.c.call(null,b,c,d,e,g,h,k,l,m,n,p,r)}function n(a,b,c,d,e,g,h,k,l,m,n,p){a=this;return a.c.ea?a.c.ea(b,c,d,e,g,h,k,l,m,n,p):a.c.call(null,b,c,d,e,g,h,k,l,m,n,p)}function p(a,b,c,d,e,g,h,k,l,m,n){a=this;return a.c.da?a.c.da(b,c,d,e,g,h,k,l,m,n):a.c.call(null,b,c,d,e,g,h,k,l,m,n)}function r(a,b,c,d,e,g,h,k,l,m){a=this;return a.c.qa?a.c.qa(b,c,d,e,g,h,k,l,m):a.c.call(null,b,c,d,e,g,h,k,l,m)}function t(a,b,c,d,e,g,h,k,l){a=this;return a.c.pa?a.c.pa(b,c,
d,e,g,h,k,l):a.c.call(null,b,c,d,e,g,h,k,l)}function w(a,b,c,d,e,g,h,k){a=this;return a.c.oa?a.c.oa(b,c,d,e,g,h,k):a.c.call(null,b,c,d,e,g,h,k)}function x(a,b,c,d,e,g,h){a=this;return a.c.W?a.c.W(b,c,d,e,g,h):a.c.call(null,b,c,d,e,g,h)}function A(a,b,c,d,e,g){a=this;return a.c.w?a.c.w(b,c,d,e,g):a.c.call(null,b,c,d,e,g)}function D(a,b,c,d,e){a=this;return a.c.p?a.c.p(b,c,d,e):a.c.call(null,b,c,d,e)}function K(a,b,c,d){a=this;return a.c.e?a.c.e(b,c,d):a.c.call(null,b,c,d)}function T(a,b,c){a=this;
return a.c.a?a.c.a(b,c):a.c.call(null,b,c)}function ma(a,b){a=this;return a.c.d?a.c.d(b):a.c.call(null,b)}function Pa(a){a=this;return a.c.q?a.c.q():a.c.call(null)}var y=null,y=function(y,ca,fa,ha,la,oa,sa,ta,xa,Da,Ga,Oa,Ya,fb,qb,Eb,Pb,qc,$c,Ed,Le,If){switch(arguments.length){case 1:return Pa.call(this,y);case 2:return ma.call(this,y,ca);case 3:return T.call(this,y,ca,fa);case 4:return K.call(this,y,ca,fa,ha);case 5:return D.call(this,y,ca,fa,ha,la);case 6:return A.call(this,y,ca,fa,ha,la,oa);case 7:return x.call(this,
y,ca,fa,ha,la,oa,sa);case 8:return w.call(this,y,ca,fa,ha,la,oa,sa,ta);case 9:return t.call(this,y,ca,fa,ha,la,oa,sa,ta,xa);case 10:return r.call(this,y,ca,fa,ha,la,oa,sa,ta,xa,Da);case 11:return p.call(this,y,ca,fa,ha,la,oa,sa,ta,xa,Da,Ga);case 12:return n.call(this,y,ca,fa,ha,la,oa,sa,ta,xa,Da,Ga,Oa);case 13:return m.call(this,y,ca,fa,ha,la,oa,sa,ta,xa,Da,Ga,Oa,Ya);case 14:return l.call(this,y,ca,fa,ha,la,oa,sa,ta,xa,Da,Ga,Oa,Ya,fb);case 15:return k.call(this,y,ca,fa,ha,la,oa,sa,ta,xa,Da,Ga,Oa,
Ya,fb,qb);case 16:return h.call(this,y,ca,fa,ha,la,oa,sa,ta,xa,Da,Ga,Oa,Ya,fb,qb,Eb);case 17:return g.call(this,y,ca,fa,ha,la,oa,sa,ta,xa,Da,Ga,Oa,Ya,fb,qb,Eb,Pb);case 18:return e.call(this,y,ca,fa,ha,la,oa,sa,ta,xa,Da,Ga,Oa,Ya,fb,qb,Eb,Pb,qc);case 19:return d.call(this,y,ca,fa,ha,la,oa,sa,ta,xa,Da,Ga,Oa,Ya,fb,qb,Eb,Pb,qc,$c);case 20:return c.call(this,y,ca,fa,ha,la,oa,sa,ta,xa,Da,Ga,Oa,Ya,fb,qb,Eb,Pb,qc,$c,Ed);case 21:return b.call(this,y,ca,fa,ha,la,oa,sa,ta,xa,Da,Ga,Oa,Ya,fb,qb,Eb,Pb,qc,$c,Ed,
Le);case 22:return a.call(this,y,ca,fa,ha,la,oa,sa,ta,xa,Da,Ga,Oa,Ya,fb,qb,Eb,Pb,qc,$c,Ed,Le,If)}throw Error("Invalid arity: "+arguments.length);};y.d=Pa;y.a=ma;y.e=T;y.p=K;y.w=D;y.W=A;y.oa=x;y.pa=w;y.qa=t;y.da=r;y.ea=p;y.fa=n;y.ga=m;y.ha=l;y.ia=k;y.ja=h;y.ka=g;y.la=e;y.ma=d;y.na=c;y.ob=b;y.Pa=a;return y}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.q=function(){return this.c.q?this.c.q():this.c.call(null)};
f.d=function(a){return this.c.d?this.c.d(a):this.c.call(null,a)};f.a=function(a,b){return this.c.a?this.c.a(a,b):this.c.call(null,a,b)};f.e=function(a,b,c){return this.c.e?this.c.e(a,b,c):this.c.call(null,a,b,c)};f.p=function(a,b,c,d){return this.c.p?this.c.p(a,b,c,d):this.c.call(null,a,b,c,d)};f.w=function(a,b,c,d,e){return this.c.w?this.c.w(a,b,c,d,e):this.c.call(null,a,b,c,d,e)};f.W=function(a,b,c,d,e,g){return this.c.W?this.c.W(a,b,c,d,e,g):this.c.call(null,a,b,c,d,e,g)};
f.oa=function(a,b,c,d,e,g,h){return this.c.oa?this.c.oa(a,b,c,d,e,g,h):this.c.call(null,a,b,c,d,e,g,h)};f.pa=function(a,b,c,d,e,g,h,k){return this.c.pa?this.c.pa(a,b,c,d,e,g,h,k):this.c.call(null,a,b,c,d,e,g,h,k)};f.qa=function(a,b,c,d,e,g,h,k,l){return this.c.qa?this.c.qa(a,b,c,d,e,g,h,k,l):this.c.call(null,a,b,c,d,e,g,h,k,l)};f.da=function(a,b,c,d,e,g,h,k,l,m){return this.c.da?this.c.da(a,b,c,d,e,g,h,k,l,m):this.c.call(null,a,b,c,d,e,g,h,k,l,m)};
f.ea=function(a,b,c,d,e,g,h,k,l,m,n){return this.c.ea?this.c.ea(a,b,c,d,e,g,h,k,l,m,n):this.c.call(null,a,b,c,d,e,g,h,k,l,m,n)};f.fa=function(a,b,c,d,e,g,h,k,l,m,n,p){return this.c.fa?this.c.fa(a,b,c,d,e,g,h,k,l,m,n,p):this.c.call(null,a,b,c,d,e,g,h,k,l,m,n,p)};f.ga=function(a,b,c,d,e,g,h,k,l,m,n,p,r){return this.c.ga?this.c.ga(a,b,c,d,e,g,h,k,l,m,n,p,r):this.c.call(null,a,b,c,d,e,g,h,k,l,m,n,p,r)};
f.ha=function(a,b,c,d,e,g,h,k,l,m,n,p,r,t){return this.c.ha?this.c.ha(a,b,c,d,e,g,h,k,l,m,n,p,r,t):this.c.call(null,a,b,c,d,e,g,h,k,l,m,n,p,r,t)};f.ia=function(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w){return this.c.ia?this.c.ia(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w):this.c.call(null,a,b,c,d,e,g,h,k,l,m,n,p,r,t,w)};f.ja=function(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x){return this.c.ja?this.c.ja(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x):this.c.call(null,a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x)};
f.ka=function(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A){return this.c.ka?this.c.ka(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A):this.c.call(null,a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A)};f.la=function(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D){return this.c.la?this.c.la(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D):this.c.call(null,a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D)};
f.ma=function(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K){return this.c.ma?this.c.ma(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K):this.c.call(null,a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K)};f.na=function(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T){return this.c.na?this.c.na(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T):this.c.call(null,a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T)};
f.ob=function(a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T,ma){var Pa=this.c;return yc.Pa?yc.Pa(Pa,a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T,ma):yc.call(null,Pa,a,b,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T,ma)};function zc(a){var b=null!=a;return(b?a?a.f&131072||a.tb||(a.f?0:z(cb,a)):z(cb,a):b)?db(a):null}function Ac(a){return null==a?!1:a?a.f&1024||a.rb?!0:a.f?!1:z(Va,a):z(Va,a)}function Bc(a){return a?a.f&16384||a.Lb?!0:a.f?!1:z($a,a):z($a,a)}function Cc(a){return a?a.m&512||a.Fb?!0:!1:!1}
function Dc(a){var b=[];ia(a,function(a,b){return function(a,c){return b.push(c)}}(a,b));return b}function Ec(a,b,c,d,e){for(;0!==e;)c[d]=a[b],d+=1,--e,b+=1}var Fc={};function Gc(a){return null==a?!1:a?a.f&64||a.Sa?!0:a.f?!1:z(Ra,a):z(Ra,a)}function Hc(a){return v(a)?!0:!1}function Ic(a,b){var c=L(b);if(c){var d=N(c),c=O(c);return Ia?Ia(a,d,c):Ja.call(null,a,d,c)}return a.q?a.q():a.call(null)}function Jc(a,b,c){for(c=L(c);;)if(c){var d=N(c);b=a.a?a.a(b,d):a.call(null,b,d);c=O(c)}else return b}
function Ja(){switch(arguments.length){case 2:return Kc(arguments[0],arguments[1]);case 3:return Ia(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}function Kc(a,b){return b&&(b.f&524288||b.vb)?b.K(null,a):Aa(b)?gc(b,a):"string"===typeof b?gc(b,a):z(hb,b)?ib.a(b,a):Ic(a,b)}function Ia(a,b,c){return c&&(c.f&524288||c.vb)?c.L(null,a,b):Aa(c)?hc(c,a,b):"string"===typeof c?hc(c,a,b):z(hb,c)?ib.e(c,a,b):Jc(a,b,c)}
function Lc(a){return a}var Mc=function Mc(){switch(arguments.length){case 0:return Mc.q();case 1:return Mc.d(arguments[0]);case 2:return Mc.a(arguments[0],arguments[1]);default:return Mc.i(arguments[0],arguments[1],new M(Array.prototype.slice.call(arguments,2),0))}};Mc.q=function(){return 0};Mc.d=function(a){return a};Mc.a=function(a,b){return a+b};Mc.i=function(a,b,c){return Ia(Mc,a+b,c)};Mc.s=function(a){var b=N(a),c=O(a);a=N(c);c=O(c);return Mc.i(b,a,c)};Mc.t=2;
var Nc=function Nc(){switch(arguments.length){case 1:return Nc.d(arguments[0]);case 2:return Nc.a(arguments[0],arguments[1]);default:return Nc.i(arguments[0],arguments[1],new M(Array.prototype.slice.call(arguments,2),0))}};Nc.d=function(a){return-a};Nc.a=function(a,b){return a-b};Nc.i=function(a,b,c){return Ia(Nc,a-b,c)};Nc.s=function(a){var b=N(a),c=O(a);a=N(c);c=O(c);return Nc.i(b,a,c)};Nc.t=2;
var Oc=function Oc(){switch(arguments.length){case 0:return Oc.q();case 1:return Oc.d(arguments[0]);case 2:return Oc.a(arguments[0],arguments[1]);default:return Oc.i(arguments[0],arguments[1],new M(Array.prototype.slice.call(arguments,2),0))}};Oc.q=function(){return 1};Oc.d=function(a){return a};Oc.a=function(a,b){return a*b};Oc.i=function(a,b,c){return Ia(Oc,a*b,c)};Oc.s=function(a){var b=N(a),c=O(a);a=N(c);c=O(c);return Oc.i(b,a,c)};Oc.t=2;
function Pc(a){a=(a-a%2)/2;return 0<=a?Math.floor.d?Math.floor.d(a):Math.floor.call(null,a):Math.ceil.d?Math.ceil.d(a):Math.ceil.call(null,a)}function Qc(a){a-=a>>1&1431655765;a=(a&858993459)+(a>>2&858993459);return 16843009*(a+(a>>4)&252645135)>>24}function Rc(a){return 0<a}function Sc(a){var b=1;for(a=L(a);;)if(a&&0<b)--b,a=O(a);else return a}
var C=function C(){switch(arguments.length){case 0:return C.q();case 1:return C.d(arguments[0]);default:return C.i(arguments[0],new M(Array.prototype.slice.call(arguments,1),0))}};C.q=function(){return""};C.d=function(a){return null==a?"":ea(a)};C.i=function(a,b){for(var c=new ja(""+C(a)),d=b;;)if(v(d))c=c.append(""+C(N(d))),d=O(d);else return c.toString()};C.s=function(a){var b=N(a);a=O(a);return C.i(b,a)};C.t=1;
function lc(a,b){var c;if(b?b.f&16777216||b.Kb||(b.f?0:z(nb,b)):z(nb,b))if(jc(a)&&jc(b)&&rc(a)!==rc(b))c=!1;else a:{c=L(a);for(var d=L(b);;){if(null==c){c=null==d;break a}if(null!=d&&P.a(N(c),N(d)))c=O(c),d=O(d);else{c=!1;break a}}}else c=null;return Hc(c)}function Tc(a,b,c,d,e){this.l=a;this.first=b;this.sa=c;this.count=d;this.j=e;this.f=65937646;this.m=8192}f=Tc.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.D=function(){return this.l};
f.Q=function(){return 1===this.count?null:this.sa};f.O=function(){return this.count};f.A=function(){var a=this.j;return null!=a?a:this.j=a=Zb(this)};f.k=function(a,b){return lc(this,b)};f.K=function(a,b){return Ic(b,this)};f.L=function(a,b,c){return Jc(b,c,this)};f.M=function(){return this.first};f.R=function(){return 1===this.count?Vb:this.sa};f.v=function(){return this};f.I=function(a,b){return new Tc(b,this.first,this.sa,this.count,this.j)};
f.G=function(a,b){return new Tc(this.l,b,this,this.count+1,null)};Tc.prototype[Ca]=function(){return Xb(this)};function Uc(a){this.l=a;this.f=65937614;this.m=8192}f=Uc.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.D=function(){return this.l};f.Q=function(){return null};f.O=function(){return 0};f.A=function(){return $b};f.k=function(a,b){return lc(this,b)};f.K=function(a,b){return Ic(b,this)};f.L=function(a,b,c){return Jc(b,c,this)};f.M=function(){return null};
f.R=function(){return Vb};f.v=function(){return null};f.I=function(a,b){return new Uc(b)};f.G=function(a,b){return new Tc(this.l,b,null,1,null)};var Vb=new Uc(null);Uc.prototype[Ca]=function(){return Xb(this)};
function Vc(){a:{var a=0<arguments.length?new M(Array.prototype.slice.call(arguments,0),0):null,b;if(a instanceof M&&0===a.h)b=a.b;else b:for(b=[];;)if(null!=a)b.push(a.M(null)),a=a.Q(null);else break b;for(var a=b.length,c=Vb;;)if(0<a)var d=a-1,c=c.G(null,b[a-1]),a=d;else break a}return c}function Wc(a,b,c,d){this.l=a;this.first=b;this.sa=c;this.j=d;this.f=65929452;this.m=8192}f=Wc.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.D=function(){return this.l};
f.Q=function(){return null==this.sa?null:L(this.sa)};f.A=function(){var a=this.j;return null!=a?a:this.j=a=Zb(this)};f.k=function(a,b){return lc(this,b)};f.K=function(a,b){return Ic(b,this)};f.L=function(a,b,c){return Jc(b,c,this)};f.M=function(){return this.first};f.R=function(){return null==this.sa?Vb:this.sa};f.v=function(){return this};f.I=function(a,b){return new Wc(b,this.first,this.sa,this.j)};f.G=function(a,b){return new Wc(null,b,this,this.j)};Wc.prototype[Ca]=function(){return Xb(this)};
function Q(a,b){var c=null==b;return(c?c:b&&(b.f&64||b.Sa))?new Wc(null,a,b,null):new Wc(null,a,L(b),null)}function Xc(a){return a?a.f&33554432||a.Ib?!0:a.f?!1:z(ob,a):z(ob,a)}function U(a,b,c,d){this.Oa=a;this.name=b;this.va=c;this.Ba=d;this.f=2153775105;this.m=4096}f=U.prototype;f.toString=function(){return[C(":"),C(this.va)].join("")};f.equiv=function(a){return this.k(null,a)};f.k=function(a,b){return b instanceof U?this.va===b.va:!1};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return S(c,this);case 3:return tc(c,this,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return S(c,this)};a.e=function(a,c,d){return tc(c,this,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.d=function(a){return S(a,this)};f.a=function(a,b){return tc(a,this,b)};
f.A=function(){var a=this.Ba;return null!=a?a:this.Ba=a=Sb(Mb(this.name),Qb(this.Oa))+2654435769|0};f.r=function(a,b){return J(b,[C(":"),C(this.va)].join(""))};var Yc=function Yc(){switch(arguments.length){case 1:return Yc.d(arguments[0]);case 2:return Yc.a(arguments[0],arguments[1]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}};
Yc.d=function(a){if(a instanceof U)return a;if(a instanceof Tb){var b;if(a&&(a.m&4096||a.ub))b=a.Oa;else throw Error([C("Doesn't support namespace: "),C(a)].join(""));return new U(b,Zc.d?Zc.d(a):Zc.call(null,a),a.xa,null)}return"string"===typeof a?(b=a.split("/"),2===b.length?new U(b[0],b[1],a,null):new U(null,b[0],a,null)):null};Yc.a=function(a,b){return new U(a,b,[C(v(a)?[C(a),C("/")].join(""):null),C(b)].join(""),null)};Yc.t=2;
function ad(a,b,c,d){this.l=a;this.Ha=b;this.n=c;this.j=d;this.f=32374988;this.m=0}f=ad.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};function bd(a){null!=a.Ha&&(a.n=a.Ha.q?a.Ha.q():a.Ha.call(null),a.Ha=null);return a.n}f.D=function(){return this.l};f.Q=function(){mb(this);return null==this.n?null:O(this.n)};f.A=function(){var a=this.j;return null!=a?a:this.j=a=Zb(this)};f.k=function(a,b){return lc(this,b)};f.K=function(a,b){return Ic(b,this)};
f.L=function(a,b,c){return Jc(b,c,this)};f.M=function(){mb(this);return null==this.n?null:N(this.n)};f.R=function(){mb(this);return null!=this.n?Ub(this.n):Vb};f.v=function(){bd(this);if(null==this.n)return null;for(var a=this.n;;)if(a instanceof ad)a=bd(a);else return this.n=a,L(this.n)};f.I=function(a,b){return new ad(b,this.Ha,this.n,this.j)};f.G=function(a,b){return Q(b,this)};ad.prototype[Ca]=function(){return Xb(this)};function cd(a,b){this.Xa=a;this.end=b;this.f=2;this.m=0}
cd.prototype.add=function(a){this.Xa[this.end]=a;return this.end+=1};cd.prototype.$=function(){var a=new dd(this.Xa,0,this.end);this.Xa=null;return a};cd.prototype.O=function(){return this.end};function dd(a,b,c){this.b=a;this.F=b;this.end=c;this.f=524306;this.m=0}f=dd.prototype;f.O=function(){return this.end-this.F};f.J=function(a,b){return this.b[this.F+b]};f.T=function(a,b,c){return 0<=b&&b<this.end-this.F?this.b[this.F+b]:c};
f.fb=function(){if(this.F===this.end)throw Error("-drop-first of empty chunk");return new dd(this.b,this.F+1,this.end)};f.K=function(a,b){return ic(this.b,b,this.b[this.F],this.F+1)};f.L=function(a,b,c){return ic(this.b,b,c,this.F)};function ed(a,b,c,d){this.$=a;this.ba=b;this.l=c;this.j=d;this.f=31850732;this.m=1536}f=ed.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.D=function(){return this.l};
f.Q=function(){if(1<Ma(this.$))return new ed(yb(this.$),this.ba,this.l,null);var a=mb(this.ba);return null==a?null:a};f.A=function(){var a=this.j;return null!=a?a:this.j=a=Zb(this)};f.k=function(a,b){return lc(this,b)};f.M=function(){return F.a(this.$,0)};f.R=function(){return 1<Ma(this.$)?new ed(yb(this.$),this.ba,this.l,null):null==this.ba?Vb:this.ba};f.v=function(){return this};f.Za=function(){return this.$};f.$a=function(){return null==this.ba?Vb:this.ba};
f.I=function(a,b){return new ed(this.$,this.ba,b,this.j)};f.G=function(a,b){return Q(b,this)};f.Ya=function(){return null==this.ba?null:this.ba};ed.prototype[Ca]=function(){return Xb(this)};function fd(a,b){return 0===Ma(a)?b:new ed(a,b,null,null)}function gd(a,b){a.add(b)}function hd(a){for(var b=[];;)if(L(a))b.push(N(a)),a=O(a);else return b}function id(a,b){if(jc(a))return rc(a);for(var c=a,d=b,e=0;;)if(0<d&&L(c))c=O(c),--d,e+=1;else return e}
var jd=function jd(b){return null==b?null:null==O(b)?L(N(b)):Q(N(b),jd(O(b)))};function kd(a){return vb(a)}var ld=function ld(){switch(arguments.length){case 0:return ld.q();case 1:return ld.d(arguments[0]);case 2:return ld.a(arguments[0],arguments[1]);default:return ld.i(arguments[0],arguments[1],new M(Array.prototype.slice.call(arguments,2),0))}};ld.q=function(){return tb(pc)};ld.d=function(a){return a};ld.a=function(a,b){return ub(a,b)};
ld.i=function(a,b,c){for(;;)if(a=ub(a,b),v(c))b=N(c),c=O(c);else return a};ld.s=function(a){var b=N(a),c=O(a);a=N(c);c=O(c);return ld.i(b,a,c)};ld.t=2;
function md(a,b,c){var d=L(c);if(0===b)return a.q?a.q():a.call(null);c=G(d);var e=H(d);if(1===b)return a.d?a.d(c):a.d?a.d(c):a.call(null,c);var d=G(e),g=H(e);if(2===b)return a.a?a.a(c,d):a.a?a.a(c,d):a.call(null,c,d);var e=G(g),h=H(g);if(3===b)return a.e?a.e(c,d,e):a.e?a.e(c,d,e):a.call(null,c,d,e);var g=G(h),k=H(h);if(4===b)return a.p?a.p(c,d,e,g):a.p?a.p(c,d,e,g):a.call(null,c,d,e,g);var h=G(k),l=H(k);if(5===b)return a.w?a.w(c,d,e,g,h):a.w?a.w(c,d,e,g,h):a.call(null,c,d,e,g,h);var k=G(l),m=H(l);
if(6===b)return a.W?a.W(c,d,e,g,h,k):a.W?a.W(c,d,e,g,h,k):a.call(null,c,d,e,g,h,k);var l=G(m),n=H(m);if(7===b)return a.oa?a.oa(c,d,e,g,h,k,l):a.oa?a.oa(c,d,e,g,h,k,l):a.call(null,c,d,e,g,h,k,l);var m=G(n),p=H(n);if(8===b)return a.pa?a.pa(c,d,e,g,h,k,l,m):a.pa?a.pa(c,d,e,g,h,k,l,m):a.call(null,c,d,e,g,h,k,l,m);var n=G(p),r=H(p);if(9===b)return a.qa?a.qa(c,d,e,g,h,k,l,m,n):a.qa?a.qa(c,d,e,g,h,k,l,m,n):a.call(null,c,d,e,g,h,k,l,m,n);var p=G(r),t=H(r);if(10===b)return a.da?a.da(c,d,e,g,h,k,l,m,n,p):a.da?
a.da(c,d,e,g,h,k,l,m,n,p):a.call(null,c,d,e,g,h,k,l,m,n,p);var r=G(t),w=H(t);if(11===b)return a.ea?a.ea(c,d,e,g,h,k,l,m,n,p,r):a.ea?a.ea(c,d,e,g,h,k,l,m,n,p,r):a.call(null,c,d,e,g,h,k,l,m,n,p,r);var t=G(w),x=H(w);if(12===b)return a.fa?a.fa(c,d,e,g,h,k,l,m,n,p,r,t):a.fa?a.fa(c,d,e,g,h,k,l,m,n,p,r,t):a.call(null,c,d,e,g,h,k,l,m,n,p,r,t);var w=G(x),A=H(x);if(13===b)return a.ga?a.ga(c,d,e,g,h,k,l,m,n,p,r,t,w):a.ga?a.ga(c,d,e,g,h,k,l,m,n,p,r,t,w):a.call(null,c,d,e,g,h,k,l,m,n,p,r,t,w);var x=G(A),D=H(A);
if(14===b)return a.ha?a.ha(c,d,e,g,h,k,l,m,n,p,r,t,w,x):a.ha?a.ha(c,d,e,g,h,k,l,m,n,p,r,t,w,x):a.call(null,c,d,e,g,h,k,l,m,n,p,r,t,w,x);var A=G(D),K=H(D);if(15===b)return a.ia?a.ia(c,d,e,g,h,k,l,m,n,p,r,t,w,x,A):a.ia?a.ia(c,d,e,g,h,k,l,m,n,p,r,t,w,x,A):a.call(null,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A);var D=G(K),T=H(K);if(16===b)return a.ja?a.ja(c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D):a.ja?a.ja(c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D):a.call(null,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D);var K=G(T),ma=H(T);if(17===b)return a.ka?
a.ka(c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K):a.ka?a.ka(c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K):a.call(null,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K);var T=G(ma),Pa=H(ma);if(18===b)return a.la?a.la(c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T):a.la?a.la(c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T):a.call(null,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T);ma=G(Pa);Pa=H(Pa);if(19===b)return a.ma?a.ma(c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T,ma):a.ma?a.ma(c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T,ma):a.call(null,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T,ma);var y=
G(Pa);H(Pa);if(20===b)return a.na?a.na(c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T,ma,y):a.na?a.na(c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T,ma,y):a.call(null,c,d,e,g,h,k,l,m,n,p,r,t,w,x,A,D,K,T,ma,y);throw Error("Only up to 20 arguments supported on functions");}
function yc(){switch(arguments.length){case 2:return nd(arguments[0],arguments[1]);case 3:return od(arguments[0],arguments[1],arguments[2]);case 4:var a;a=arguments[0];var b=Q(arguments[1],Q(arguments[2],arguments[3])),c=a.t;if(a.s){var d=id(b,c+1);a=d<=c?md(a,d,b):a.s(b)}else a=a.apply(a,hd(b));return a;case 5:return pd(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:return qd(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],new M(Array.prototype.slice.call(arguments,
5),0))}}function nd(a,b){var c=a.t;if(a.s){var d=id(b,c+1);return d<=c?md(a,d,b):a.s(b)}return a.apply(a,hd(b))}function od(a,b,c){b=Q(b,c);c=a.t;if(a.s){var d=id(b,c+1);return d<=c?md(a,d,b):a.s(b)}return a.apply(a,hd(b))}function pd(a,b,c,d,e){b=Q(b,Q(c,Q(d,e)));c=a.t;return a.s?(d=id(b,c+1),d<=c?md(a,d,b):a.s(b)):a.apply(a,hd(b))}function qd(a,b,c,d,e,g){b=Q(b,Q(c,Q(d,Q(e,jd(g)))));c=a.t;return a.s?(d=id(b,c+1),d<=c?md(a,d,b):a.s(b)):a.apply(a,hd(b))}
function rd(a,b){for(;;){if(null==L(b))return!0;var c;c=N(b);c=a.d?a.d(c):a.call(null,c);if(v(c)){c=a;var d=O(b);a=c;b=d}else return!1}}function sd(a){for(var b=Lc;;)if(L(a)){var c;c=N(a);c=b.d?b.d(c):b.call(null,c);if(v(c))return c;a=O(a)}else return null}
function td(a,b){return function d(b,g){return new ad(null,function(){var h=L(g);if(h){if(Cc(h)){for(var k=zb(h),l=rc(k),m=new cd(Array(l),0),n=0;;)if(n<l)gd(m,function(){var d=b+n,g=F.a(k,n);return a.a?a.a(d,g):a.call(null,d,g)}()),n+=1;else break;return fd(m.$(),d(b+l,Ab(h)))}return Q(function(){var d=N(h);return a.a?a.a(b,d):a.call(null,b,d)}(),d(b+1,Ub(h)))}return null},null,null)}(0,b)}function ud(a,b,c,d){this.state=a;this.l=b;this.Eb=c;this.jb=d;this.m=16386;this.f=6455296}f=ud.prototype;
f.equiv=function(a){return this.k(null,a)};f.k=function(a,b){return this===b};f.nb=function(){return this.state};f.D=function(){return this.l};f.hb=function(a,b,c){for(var d=L(this.jb),e=null,g=0,h=0;;)if(h<g){a=e.J(null,h);var k=R(a,0);a=R(a,1);var l=b,m=c;a.p?a.p(k,this,l,m):a.call(null,k,this,l,m);h+=1}else if(a=L(d))d=a,Cc(d)?(e=zb(d),d=Ab(d),a=e,g=rc(e),e=a):(a=N(d),k=R(a,0),a=R(a,1),e=k,g=b,h=c,a.p?a.p(e,this,g,h):a.call(null,e,this,g,h),d=O(d),e=null,g=0),h=0;else return null};
f.A=function(){return this[ba]||(this[ba]=++da)};function vd(){switch(arguments.length){case 1:return wd(arguments[0]);default:var a=arguments[0],b=new M(Array.prototype.slice.call(arguments,1),0),c=Gc(b)?nd(xd,b):b,b=S(c,wa),c=S(c,yd);return new ud(a,b,c,null)}}function wd(a){return new ud(a,null,null,null)}
function zd(a,b){if(a instanceof ud){var c=a.Eb;if(null!=c&&!v(c.d?c.d(b):c.call(null,b)))throw Error([C("Assert failed: "),C("Validator rejected reference state"),C("\n"),C(function(){var a=Vc(new Tb(null,"validate","validate",1439230700,null),new Tb(null,"new-value","new-value",-1567397401,null));return Ad.d?Ad.d(a):Ad.call(null,a)}())].join(""));c=a.state;a.state=b;null!=a.jb&&sb(a,c,b);return b}return Cb(a,b)}
var Bd=function Bd(){switch(arguments.length){case 2:return Bd.a(arguments[0],arguments[1]);case 3:return Bd.e(arguments[0],arguments[1],arguments[2]);case 4:return Bd.p(arguments[0],arguments[1],arguments[2],arguments[3]);default:return Bd.i(arguments[0],arguments[1],arguments[2],arguments[3],new M(Array.prototype.slice.call(arguments,4),0))}};Bd.a=function(a,b){var c;a instanceof ud?(c=a.state,c=b.d?b.d(c):b.call(null,c),c=zd(a,c)):c=Db.a(a,b);return c};
Bd.e=function(a,b,c){if(a instanceof ud){var d=a.state;b=b.a?b.a(d,c):b.call(null,d,c);a=zd(a,b)}else a=Db.e(a,b,c);return a};Bd.p=function(a,b,c,d){if(a instanceof ud){var e=a.state;b=b.e?b.e(e,c,d):b.call(null,e,c,d);a=zd(a,b)}else a=Db.p(a,b,c,d);return a};Bd.i=function(a,b,c,d,e){return a instanceof ud?zd(a,pd(b,a.state,c,d,e)):Db.w(a,b,c,d,e)};Bd.s=function(a){var b=N(a),c=O(a);a=N(c);var d=O(c),c=N(d),e=O(d),d=N(e),e=O(e);return Bd.i(b,a,c,d,e)};Bd.t=4;
var V=function V(){switch(arguments.length){case 1:return V.d(arguments[0]);case 2:return V.a(arguments[0],arguments[1]);case 3:return V.e(arguments[0],arguments[1],arguments[2]);case 4:return V.p(arguments[0],arguments[1],arguments[2],arguments[3]);default:return V.i(arguments[0],arguments[1],arguments[2],arguments[3],new M(Array.prototype.slice.call(arguments,4),0))}};
V.d=function(a){return function(b){return function(){function c(c,d){var e=a.d?a.d(d):a.call(null,d);return b.a?b.a(c,e):b.call(null,c,e)}function d(a){return b.d?b.d(a):b.call(null,a)}function e(){return b.q?b.q():b.call(null)}var g=null,h=function(){function c(a,b,e){var g=null;if(2<arguments.length){for(var g=0,h=Array(arguments.length-2);g<h.length;)h[g]=arguments[g+2],++g;g=new M(h,0)}return d.call(this,a,b,g)}function d(c,e,g){e=od(a,e,g);return b.a?b.a(c,e):b.call(null,c,e)}c.t=2;c.s=function(a){var b=
N(a);a=O(a);var c=N(a);a=Ub(a);return d(b,c,a)};c.i=d;return c}(),g=function(a,b,g){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,a);case 2:return c.call(this,a,b);default:var n=null;if(2<arguments.length){for(var n=0,p=Array(arguments.length-2);n<p.length;)p[n]=arguments[n+2],++n;n=new M(p,0)}return h.i(a,b,n)}throw Error("Invalid arity: "+arguments.length);};g.t=2;g.s=h.s;g.q=e;g.d=d;g.a=c;g.i=h.i;return g}()}};
V.a=function(a,b){return new ad(null,function(){var c=L(b);if(c){if(Cc(c)){for(var d=zb(c),e=rc(d),g=new cd(Array(e),0),h=0;;)if(h<e)gd(g,function(){var b=F.a(d,h);return a.d?a.d(b):a.call(null,b)}()),h+=1;else break;return fd(g.$(),V.a(a,Ab(c)))}return Q(function(){var b=N(c);return a.d?a.d(b):a.call(null,b)}(),V.a(a,Ub(c)))}return null},null,null)};
V.e=function(a,b,c){return new ad(null,function(){var d=L(b),e=L(c);if(d&&e){var g=Q,h;h=N(d);var k=N(e);h=a.a?a.a(h,k):a.call(null,h,k);d=g(h,V.e(a,Ub(d),Ub(e)))}else d=null;return d},null,null)};V.p=function(a,b,c,d){return new ad(null,function(){var e=L(b),g=L(c),h=L(d);if(e&&g&&h){var k=Q,l;l=N(e);var m=N(g),n=N(h);l=a.e?a.e(l,m,n):a.call(null,l,m,n);e=k(l,V.p(a,Ub(e),Ub(g),Ub(h)))}else e=null;return e},null,null)};
V.i=function(a,b,c,d,e){var g=function k(a){return new ad(null,function(){var b=V.a(L,a);return rd(Lc,b)?Q(V.a(N,b),k(V.a(Ub,b))):null},null,null)};return V.a(function(){return function(b){return nd(a,b)}}(g),g(oc.i(e,d,nc([c,b],0))))};V.s=function(a){var b=N(a),c=O(a);a=N(c);var d=O(c),c=N(d),e=O(d),d=N(e),e=O(e);return V.i(b,a,c,d,e)};V.t=4;function Cd(a,b){return new ad(null,function(){if(0<a){var c=L(b);return c?Q(N(c),Cd(a-1,Ub(c))):null}return null},null,null)}
function Dd(a){return new ad(null,function(){return Q(a,Dd(a))},null,null)}function Fd(a,b){var c;if(null!=a)if(a&&(a.m&4||a.Gb)){c=kd(Ia(ub,tb(a),b));var d=zc(a);c=wc(c)&&!(c?c.f&262144||c.Mb||(c.f?0:z(eb,c)):z(eb,c))?new xc(c,d):null==c?null:gb(c,d)}else c=Ia(Na,a,b);else c=Ia(oc,Vb,b);return c}function Gd(a,b){return kd(Ia(function(b,d){return ld.a(b,a.d?a.d(d):a.call(null,d))},tb(pc),b))}
var W=function W(){switch(arguments.length){case 3:return W.e(arguments[0],arguments[1],arguments[2]);case 4:return W.p(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return W.w(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);case 6:return W.W(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);default:return W.i(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],new M(Array.prototype.slice.call(arguments,6),0))}};
W.e=function(a,b,c){var d=R(b,0);b=Sc(b);return v(b)?uc.e(a,d,W.e(S(a,d),b,c)):uc.e(a,d,function(){var b=S(a,d);return c.d?c.d(b):c.call(null,b)}())};W.p=function(a,b,c,d){var e=R(b,0);b=Sc(b);return v(b)?uc.e(a,e,W.p(S(a,e),b,c,d)):uc.e(a,e,function(){var b=S(a,e);return c.a?c.a(b,d):c.call(null,b,d)}())};W.w=function(a,b,c,d,e){var g=R(b,0);b=Sc(b);return v(b)?uc.e(a,g,W.w(S(a,g),b,c,d,e)):uc.e(a,g,function(){var b=S(a,g);return c.e?c.e(b,d,e):c.call(null,b,d,e)}())};
W.W=function(a,b,c,d,e,g){var h=R(b,0);b=Sc(b);return v(b)?uc.e(a,h,W.W(S(a,h),b,c,d,e,g)):uc.e(a,h,function(){var b=S(a,h);return c.p?c.p(b,d,e,g):c.call(null,b,d,e,g)}())};W.i=function(a,b,c,d,e,g,h){var k=R(b,0);b=Sc(b);return v(b)?uc.e(a,k,qd(W,S(a,k),b,c,d,nc([e,g,h],0))):uc.e(a,k,qd(c,S(a,k),d,e,g,nc([h],0)))};W.s=function(a){var b=N(a),c=O(a);a=N(c);var d=O(c),c=N(d),e=O(d),d=N(e),g=O(e),e=N(g),h=O(g),g=N(h),h=O(h);return W.i(b,a,c,d,e,g,h)};W.t=6;function Hd(a,b){this.o=a;this.b=b}
function Id(a){return new Hd(a,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null])}function Jd(a){a=a.g;return 32>a?0:a-1>>>5<<5}function Kd(a,b,c){for(;;){if(0===b)return c;var d=Id(a);d.b[0]=c;c=d;b-=5}}var Ld=function Ld(b,c,d,e){var g=new Hd(d.o,E(d.b)),h=b.g-1>>>c&31;5===c?g.b[h]=e:(d=d.b[h],b=null!=d?Ld(b,c-5,d,e):Kd(null,c-5,e),g.b[h]=b);return g};
function Md(a,b){throw Error([C("No item "),C(a),C(" in vector of length "),C(b)].join(""));}function Nd(a,b){if(b>=Jd(a))return a.P;for(var c=a.root,d=a.shift;;)if(0<d)var e=d-5,c=c.b[b>>>d&31],d=e;else return c.b}function Od(a,b){return 0<=b&&b<a.g?Nd(a,b):Md(b,a.g)}var Pd=function Pd(b,c,d,e,g){var h=new Hd(d.o,E(d.b));if(0===c)h.b[e&31]=g;else{var k=e>>>c&31;b=Pd(b,c-5,d.b[k],e,g);h.b[k]=b}return h};function Qd(a,b,c,d,e,g){this.h=a;this.Wa=b;this.b=c;this.ta=d;this.start=e;this.end=g}
Qd.prototype.eb=function(){return this.h<this.end};Qd.prototype.next=function(){32===this.h-this.Wa&&(this.b=Nd(this.ta,this.h),this.Wa+=32);var a=this.b[this.h&31];this.h+=1;return a};function X(a,b,c,d,e,g){this.l=a;this.g=b;this.shift=c;this.root=d;this.P=e;this.j=g;this.f=167668511;this.m=8196}f=X.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.u=function(a,b){return I.e(this,b,null)};f.B=function(a,b,c){return"number"===typeof b?F.e(this,b,c):c};
f.J=function(a,b){return Od(this,b)[b&31]};f.T=function(a,b,c){return 0<=b&&b<this.g?Nd(this,b)[b&31]:c};f.cb=function(a,b,c){if(0<=b&&b<this.g)return Jd(this)<=b?(a=E(this.P),a[b&31]=c,new X(this.l,this.g,this.shift,this.root,a,null)):new X(this.l,this.g,this.shift,Pd(this,this.shift,this.root,b,c),this.P,null);if(b===this.g)return Na(this,c);throw Error([C("Index "),C(b),C(" out of bounds  [0,"),C(this.g),C("]")].join(""));};
f.Qa=function(){var a=this.g;return new Qd(0,0,0<rc(this)?Nd(this,0):null,this,0,a)};f.D=function(){return this.l};f.O=function(){return this.g};f.ab=function(){return F.a(this,0)};f.bb=function(){return F.a(this,1)};f.A=function(){var a=this.j;return null!=a?a:this.j=a=Zb(this)};f.k=function(a,b){if(b instanceof X)if(this.g===rc(b))for(var c=Fb(this),d=Fb(b);;)if(v(c.eb())){var e=c.next(),g=d.next();if(!P.a(e,g))return!1}else return!0;else return!1;else return lc(this,b)};
f.Ja=function(){var a=this;return new Rd(a.g,a.shift,function(){var b=a.root;return Sd.d?Sd.d(b):Sd.call(null,b)}(),function(){var b=a.P;return Td.d?Td.d(b):Td.call(null,b)}())};f.K=function(a,b){return ec(this,b)};f.L=function(a,b,c){a=0;for(var d=c;;)if(a<this.g){var e=Nd(this,a);c=e.length;a:for(var g=0;;)if(g<c)var h=e[g],d=b.a?b.a(d,h):b.call(null,d,h),g=g+1;else{e=d;break a}a+=c;d=e}else return d};
f.aa=function(a,b,c){if("number"===typeof b)return ab(this,b,c);throw Error("Vector's key for assoc must be a number.");};f.v=function(){if(0===this.g)return null;if(32>=this.g)return new M(this.P,0);var a;a:{a=this.root;for(var b=this.shift;;)if(0<b)b-=5,a=a.b[0];else{a=a.b;break a}}return Ud?Ud(this,a,0,0):Vd.call(null,this,a,0,0)};f.I=function(a,b){return new X(b,this.g,this.shift,this.root,this.P,this.j)};
f.G=function(a,b){if(32>this.g-Jd(this)){for(var c=this.P.length,d=Array(c+1),e=0;;)if(e<c)d[e]=this.P[e],e+=1;else break;d[c]=b;return new X(this.l,this.g+1,this.shift,this.root,d,null)}c=(d=this.g>>>5>1<<this.shift)?this.shift+5:this.shift;d?(d=Id(null),d.b[0]=this.root,e=Kd(null,this.shift,new Hd(null,this.P)),d.b[1]=e):d=Ld(this,this.shift,this.root,new Hd(null,this.P));return new X(this.l,this.g+1,c,d,[b],null)};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.J(null,c);case 3:return this.T(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.J(null,c)};a.e=function(a,c,d){return this.T(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.d=function(a){return this.J(null,a)};f.a=function(a,b){return this.T(null,a,b)};
var Y=new Hd(null,[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null]),pc=new X(null,0,5,Y,[],$b);X.prototype[Ca]=function(){return Xb(this)};function Wd(a){if(Aa(a))a:{var b=a.length;if(32>b)a=new X(null,b,5,Y,a,null);else for(var c=32,d=(new X(null,32,5,Y,a.slice(0,32),null)).Ja(null);;)if(c<b)var e=c+1,d=ld.a(d,a[c]),c=e;else{a=vb(d);break a}}else a=vb(Ia(ub,tb(pc),a));return a}
function Xd(a,b,c,d,e,g){this.V=a;this.ra=b;this.h=c;this.F=d;this.l=e;this.j=g;this.f=32375020;this.m=1536}f=Xd.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.D=function(){return this.l};f.Q=function(){if(this.F+1<this.ra.length){var a;a=this.V;var b=this.ra,c=this.h,d=this.F+1;a=Ud?Ud(a,b,c,d):Vd.call(null,a,b,c,d);return null==a?null:a}return Bb(this)};f.A=function(){var a=this.j;return null!=a?a:this.j=a=Zb(this)};
f.k=function(a,b){return lc(this,b)};f.K=function(a,b){var c;c=this.V;var d=this.h+this.F,e=rc(this.V);c=Yd?Yd(c,d,e):Zd.call(null,c,d,e);return ec(c,b)};f.L=function(a,b,c){a=this.V;var d=this.h+this.F,e=rc(this.V);a=Yd?Yd(a,d,e):Zd.call(null,a,d,e);return fc(a,b,c)};f.M=function(){return this.ra[this.F]};f.R=function(){if(this.F+1<this.ra.length){var a;a=this.V;var b=this.ra,c=this.h,d=this.F+1;a=Ud?Ud(a,b,c,d):Vd.call(null,a,b,c,d);return null==a?Vb:a}return Ab(this)};f.v=function(){return this};
f.Za=function(){var a=this.ra;return new dd(a,this.F,a.length)};f.$a=function(){var a=this.h+this.ra.length;if(a<Ma(this.V)){var b=this.V,c=Nd(this.V,a);return Ud?Ud(b,c,a,0):Vd.call(null,b,c,a,0)}return Vb};f.I=function(a,b){var c=this.V,d=this.ra,e=this.h,g=this.F;return $d?$d(c,d,e,g,b):Vd.call(null,c,d,e,g,b)};f.G=function(a,b){return Q(b,this)};f.Ya=function(){var a=this.h+this.ra.length;if(a<Ma(this.V)){var b=this.V,c=Nd(this.V,a);return Ud?Ud(b,c,a,0):Vd.call(null,b,c,a,0)}return null};
Xd.prototype[Ca]=function(){return Xb(this)};function Vd(){switch(arguments.length){case 3:var a=arguments[0],b=arguments[1],c=arguments[2];return new Xd(a,Od(a,b),b,c,null,null);case 4:return Ud(arguments[0],arguments[1],arguments[2],arguments[3]);case 5:return $d(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}function Ud(a,b,c,d){return new Xd(a,b,c,d,null,null)}
function $d(a,b,c,d,e){return new Xd(a,b,c,d,e,null)}function ae(a,b,c,d,e){this.l=a;this.ta=b;this.start=c;this.end=d;this.j=e;this.f=167666463;this.m=8192}f=ae.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.u=function(a,b){return I.e(this,b,null)};f.B=function(a,b,c){return"number"===typeof b?F.e(this,b,c):c};f.J=function(a,b){return 0>b||this.end<=this.start+b?Md(b,this.end-this.start):F.a(this.ta,this.start+b)};
f.T=function(a,b,c){return 0>b||this.end<=this.start+b?c:F.e(this.ta,this.start+b,c)};f.cb=function(a,b,c){var d=this.start+b;a=this.l;c=uc.e(this.ta,d,c);b=this.start;var e=this.end,d=d+1,d=e>d?e:d;return be.w?be.w(a,c,b,d,null):be.call(null,a,c,b,d,null)};f.D=function(){return this.l};f.O=function(){return this.end-this.start};f.A=function(){var a=this.j;return null!=a?a:this.j=a=Zb(this)};f.k=function(a,b){return lc(this,b)};f.K=function(a,b){return ec(this,b)};
f.L=function(a,b,c){return fc(this,b,c)};f.aa=function(a,b,c){if("number"===typeof b)return ab(this,b,c);throw Error("Subvec's key for assoc must be a number.");};f.v=function(){var a=this;return function(b){return function d(e){return e===a.end?null:Q(F.a(a.ta,e),new ad(null,function(){return function(){return d(e+1)}}(b),null,null))}}(this)(a.start)};f.I=function(a,b){var c=this.ta,d=this.start,e=this.end,g=this.j;return be.w?be.w(b,c,d,e,g):be.call(null,b,c,d,e,g)};
f.G=function(a,b){var c=this.l,d=ab(this.ta,this.end,b),e=this.start,g=this.end+1;return be.w?be.w(c,d,e,g,null):be.call(null,c,d,e,g,null)};f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.J(null,c);case 3:return this.T(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.J(null,c)};a.e=function(a,c,d){return this.T(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};
f.d=function(a){return this.J(null,a)};f.a=function(a,b){return this.T(null,a,b)};ae.prototype[Ca]=function(){return Xb(this)};function be(a,b,c,d,e){for(;;)if(b instanceof ae)c=b.start+c,d=b.start+d,b=b.ta;else{var g=rc(b);if(0>c||0>d||c>g||d>g)throw Error("Index out of bounds");return new ae(a,b,c,d,e)}}
function Zd(){switch(arguments.length){case 2:var a=arguments[0];return Yd(a,arguments[1],rc(a));case 3:return Yd(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}function Yd(a,b,c){return be(null,a,b,c,null)}function ce(a,b){return a===b.o?b:new Hd(a,E(b.b))}function Sd(a){return new Hd({},E(a.b))}
function Td(a){var b=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];Ec(a,0,b,0,a.length);return b}var de=function de(b,c,d,e){d=ce(b.root.o,d);var g=b.g-1>>>c&31;if(5===c)b=e;else{var h=d.b[g];b=null!=h?de(b,c-5,h,e):Kd(b.root.o,c-5,e)}d.b[g]=b;return d};function Rd(a,b,c,d){this.g=a;this.shift=b;this.root=c;this.P=d;this.m=88;this.f=275}f=Rd.prototype;
f.Ta=function(a,b){if(this.root.o){if(32>this.g-Jd(this))this.P[this.g&31]=b;else{var c=new Hd(this.root.o,this.P),d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];d[0]=b;this.P=d;if(this.g>>>5>1<<this.shift){var d=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],e=this.shift+
5;d[0]=this.root;d[1]=Kd(this.root.o,this.shift,c);this.root=new Hd(this.root.o,d);this.shift=e}else this.root=de(this,this.shift,this.root,c)}this.g+=1;return this}throw Error("conj! after persistent!");};f.Ua=function(){if(this.root.o){this.root.o=null;var a=this.g-Jd(this),b=Array(a);Ec(this.P,0,b,0,a);return new X(null,this.g,this.shift,this.root,b,null)}throw Error("persistent! called twice");};
f.Ka=function(a,b,c){if("number"===typeof b)return xb(this,b,c);throw Error("TransientVector's key for assoc! must be a number.");};
f.gb=function(a,b,c){var d=this;if(d.root.o){if(0<=b&&b<d.g)return Jd(this)<=b?d.P[b&31]=c:(a=function(){return function g(a,k){var l=ce(d.root.o,k);if(0===a)l.b[b&31]=c;else{var m=b>>>a&31,n=g(a-5,l.b[m]);l.b[m]=n}return l}}(this).call(null,d.shift,d.root),d.root=a),this;if(b===d.g)return ub(this,c);throw Error([C("Index "),C(b),C(" out of bounds for TransientVector of length"),C(d.g)].join(""));}throw Error("assoc! after persistent!");};
f.O=function(){if(this.root.o)return this.g;throw Error("count after persistent!");};f.J=function(a,b){if(this.root.o)return Od(this,b)[b&31];throw Error("nth after persistent!");};f.T=function(a,b,c){return 0<=b&&b<this.g?F.a(this,b):c};f.u=function(a,b){return I.e(this,b,null)};f.B=function(a,b,c){return"number"===typeof b?F.e(this,b,c):c};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.u(null,c);case 3:return this.B(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.u(null,c)};a.e=function(a,c,d){return this.B(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.d=function(a){return this.u(null,a)};f.a=function(a,b){return this.B(null,a,b)};function ee(){this.f=2097152;this.m=0}
ee.prototype.equiv=function(a){return this.k(null,a)};ee.prototype.k=function(){return!1};var fe=new ee;function ge(a,b){return Hc(Ac(b)?rc(a)===rc(b)?rd(Lc,V.a(function(a){return P.a(tc(b,N(a),fe),N(O(a)))},a)):null:null)}function he(a){this.n=a}he.prototype.next=function(){if(null!=this.n){var a=N(this.n),b=R(a,0),a=R(a,1);this.n=O(this.n);return{value:[b,a],done:!1}}return{value:null,done:!0}};function ie(a){return new he(L(a))}
function je(a,b){var c;if(b instanceof U)a:{c=a.length;for(var d=b.va,e=0;;){if(c<=e){c=-1;break a}var g=a[e];if(g instanceof U&&d===g.va){c=e;break a}e+=2}}else if(c="string"==typeof b,v(v(c)?c:"number"===typeof b))a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(b===a[d]){c=d;break a}d+=2}else if(b instanceof Tb)a:for(c=a.length,d=b.xa,e=0;;){if(c<=e){c=-1;break a}g=a[e];if(g instanceof Tb&&d===g.xa){c=e;break a}e+=2}else if(null==b)a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(null==a[d]){c=
d;break a}d+=2}else a:for(c=a.length,d=0;;){if(c<=d){c=-1;break a}if(P.a(b,a[d])){c=d;break a}d+=2}return c}function ke(a,b,c){this.b=a;this.h=b;this.S=c;this.f=32374990;this.m=0}f=ke.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.D=function(){return this.S};f.Q=function(){return this.h<this.b.length-2?new ke(this.b,this.h+2,this.S):null};f.O=function(){return(this.b.length-this.h)/2};f.A=function(){return Zb(this)};f.k=function(a,b){return lc(this,b)};
f.K=function(a,b){return Ic(b,this)};f.L=function(a,b,c){return Jc(b,c,this)};f.M=function(){return new X(null,2,5,Y,[this.b[this.h],this.b[this.h+1]],null)};f.R=function(){return this.h<this.b.length-2?new ke(this.b,this.h+2,this.S):Vb};f.v=function(){return this};f.I=function(a,b){return new ke(this.b,this.h,b)};f.G=function(a,b){return Q(b,this)};ke.prototype[Ca]=function(){return Xb(this)};function le(a,b,c){this.b=a;this.h=b;this.g=c}le.prototype.eb=function(){return this.h<this.g};
le.prototype.next=function(){var a=new X(null,2,5,Y,[this.b[this.h],this.b[this.h+1]],null);this.h+=2;return a};function u(a,b,c,d){this.l=a;this.g=b;this.b=c;this.j=d;this.f=16647951;this.m=8196}f=u.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.keys=function(){return Xb(me.d?me.d(this):me.call(null,this))};f.entries=function(){return ie(L(this))};f.values=function(){return Xb(ne.d?ne.d(this):ne.call(null,this))};
f.has=function(a){return tc(this,a,Fc)===Fc?!1:!0};f.get=function(a,b){return this.B(null,a,b)};f.forEach=function(a){for(var b=L(this),c=null,d=0,e=0;;)if(e<d){var g=c.J(null,e),h=R(g,0),g=R(g,1);a.a?a.a(g,h):a.call(null,g,h);e+=1}else if(b=L(b))Cc(b)?(c=zb(b),b=Ab(b),h=c,d=rc(c),c=h):(c=N(b),h=R(c,0),c=g=R(c,1),a.a?a.a(c,h):a.call(null,c,h),b=O(b),c=null,d=0),e=0;else return null};f.u=function(a,b){return I.e(this,b,null)};f.B=function(a,b,c){a=je(this.b,b);return-1===a?c:this.b[a+1]};
f.Qa=function(){return new le(this.b,0,2*this.g)};f.D=function(){return this.l};f.O=function(){return this.g};f.A=function(){var a=this.j;return null!=a?a:this.j=a=ac(this)};f.k=function(a,b){if(b&&(b.f&1024||b.rb)){var c=this.b.length;if(this.g===b.O(null))for(var d=0;;)if(d<c){var e=b.B(null,this.b[d],Fc);if(e!==Fc)if(P.a(this.b[d+1],e))d+=2;else return!1;else return!1}else return!0;else return!1}else return ge(this,b)};f.Ja=function(){return new oe({},this.b.length,E(this.b))};
f.K=function(a,b){return Ic(b,this)};f.L=function(a,b,c){return Jc(b,c,this)};f.aa=function(a,b,c){a=je(this.b,b);if(-1===a){if(this.g<pe){a=this.b;for(var d=a.length,e=Array(d+2),g=0;;)if(g<d)e[g]=a[g],g+=1;else break;e[d]=b;e[d+1]=c;return new u(this.l,this.g+1,e,null)}return gb(Ua(Fd(vc,this),b,c),this.l)}if(c===this.b[a+1])return this;b=E(this.b);b[a+1]=c;return new u(this.l,this.g,b,null)};f.v=function(){var a=this.b;return 0<=a.length-2?new ke(a,0,null):null};
f.I=function(a,b){return new u(b,this.g,this.b,this.j)};f.G=function(a,b){if(Bc(b))return Ua(this,F.a(b,0),F.a(b,1));for(var c=this,d=L(b);;){if(null==d)return c;var e=N(d);if(Bc(e))c=Ua(c,F.a(e,0),F.a(e,1)),d=O(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.u(null,c);case 3:return this.B(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.u(null,c)};a.e=function(a,c,d){return this.B(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.d=function(a){return this.u(null,a)};f.a=function(a,b){return this.B(null,a,b)};var qe=new u(null,0,[],bc),pe=8;
function re(a){for(var b=[],c=0;;)if(c<a.length){var d=a[c],e=a[c+1];-1===je(b,d)&&(b.push(d),b.push(e));c+=2}else break;return new u(null,b.length/2,b,null)}u.prototype[Ca]=function(){return Xb(this)};function oe(a,b,c){this.Ga=a;this.Ia=b;this.b=c;this.f=258;this.m=56}f=oe.prototype;f.O=function(){if(v(this.Ga))return Pc(this.Ia);throw Error("count after persistent!");};f.u=function(a,b){return I.e(this,b,null)};
f.B=function(a,b,c){if(v(this.Ga))return a=je(this.b,b),-1===a?c:this.b[a+1];throw Error("lookup after persistent!");};
f.Ta=function(a,b){if(v(this.Ga)){if(b?b.f&2048||b.sb||(b.f?0:z(Wa,b)):z(Wa,b))return wb(this,se.d?se.d(b):se.call(null,b),te.d?te.d(b):te.call(null,b));for(var c=L(b),d=this;;){var e=N(c);if(v(e))var g=e,c=O(c),d=wb(d,function(){var a=g;return se.d?se.d(a):se.call(null,a)}(),function(){var a=g;return te.d?te.d(a):te.call(null,a)}());else return d}}else throw Error("conj! after persistent!");};
f.Ua=function(){if(v(this.Ga))return this.Ga=!1,new u(null,Pc(this.Ia),this.b,null);throw Error("persistent! called twice");};f.Ka=function(a,b,c){if(v(this.Ga)){a=je(this.b,b);if(-1===a){if(this.Ia+2<=2*pe)return this.Ia+=2,this.b.push(b),this.b.push(c),this;a=this.Ia;var d=this.b;a=ue.a?ue.a(a,d):ue.call(null,a,d);return wb(a,b,c)}c!==this.b[a+1]&&(this.b[a+1]=c);return this}throw Error("assoc! after persistent!");};
function ue(a,b){for(var c=tb(vc),d=0;;)if(d<a)c=wb(c,b[d],b[d+1]),d+=2;else return c}function ve(){this.ca=!1}function we(a,b){return a===b?!0:a===b||a instanceof U&&b instanceof U&&a.va===b.va?!0:P.a(a,b)}function xe(a,b,c){a=E(a);a[b]=c;return a}function ye(a,b,c,d){a=a.za(b);a.b[c]=d;return a}function ze(a,b,c){this.o=a;this.C=b;this.b=c}f=ze.prototype;f.za=function(a){if(a===this.o)return this;var b=Qc(this.C),c=Array(0>b?4:2*(b+1));Ec(this.b,0,c,0,2*b);return new ze(a,this.C,c)};
f.Na=function(){var a=this.b;return Ae?Ae(a):Be.call(null,a)};f.Aa=function(a,b,c,d){var e=1<<(b>>>a&31);if(0===(this.C&e))return d;var g=Qc(this.C&e-1),e=this.b[2*g],g=this.b[2*g+1];return null==e?g.Aa(a+5,b,c,d):we(c,e)?g:d};
f.Z=function(a,b,c,d,e,g){var h=1<<(c>>>b&31),k=Qc(this.C&h-1);if(0===(this.C&h)){var l=Qc(this.C);if(2*l<this.b.length){a=this.za(a);b=a.b;g.ca=!0;a:for(c=2*(l-k),g=2*k+(c-1),l=2*(k+1)+(c-1);;){if(0===c)break a;b[l]=b[g];--l;--c;--g}b[2*k]=d;b[2*k+1]=e;a.C|=h;return a}if(16<=l){k=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];k[c>>>b&31]=Ce.Z(a,b+5,c,d,e,g);for(e=d=0;;)if(32>d)0!==(this.C>>>
d&1)&&(k[d]=null!=this.b[e]?Ce.Z(a,b+5,Rb(this.b[e]),this.b[e],this.b[e+1],g):this.b[e+1],e+=2),d+=1;else break;return new De(a,l+1,k)}b=Array(2*(l+4));Ec(this.b,0,b,0,2*k);b[2*k]=d;b[2*k+1]=e;Ec(this.b,2*k,b,2*(k+1),2*(l-k));g.ca=!0;a=this.za(a);a.b=b;a.C|=h;return a}l=this.b[2*k];h=this.b[2*k+1];if(null==l)return l=h.Z(a,b+5,c,d,e,g),l===h?this:ye(this,a,2*k+1,l);if(we(d,l))return e===h?this:ye(this,a,2*k+1,e);g.ca=!0;g=b+5;d=Ee?Ee(a,g,l,h,c,d,e):Fe.call(null,a,g,l,h,c,d,e);e=2*k;k=2*k+1;a=this.za(a);
a.b[e]=null;a.b[k]=d;return a};
f.Y=function(a,b,c,d,e){var g=1<<(b>>>a&31),h=Qc(this.C&g-1);if(0===(this.C&g)){var k=Qc(this.C);if(16<=k){h=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];h[b>>>a&31]=Ce.Y(a+5,b,c,d,e);for(d=c=0;;)if(32>c)0!==(this.C>>>c&1)&&(h[c]=null!=this.b[d]?Ce.Y(a+5,Rb(this.b[d]),this.b[d],this.b[d+1],e):this.b[d+1],d+=2),c+=1;else break;return new De(null,k+1,h)}a=Array(2*(k+1));Ec(this.b,0,a,
0,2*h);a[2*h]=c;a[2*h+1]=d;Ec(this.b,2*h,a,2*(h+1),2*(k-h));e.ca=!0;return new ze(null,this.C|g,a)}var l=this.b[2*h],g=this.b[2*h+1];if(null==l)return k=g.Y(a+5,b,c,d,e),k===g?this:new ze(null,this.C,xe(this.b,2*h+1,k));if(we(c,l))return d===g?this:new ze(null,this.C,xe(this.b,2*h+1,d));e.ca=!0;e=this.C;k=this.b;a+=5;a=Ge?Ge(a,l,g,b,c,d):Fe.call(null,a,l,g,b,c,d);c=2*h;h=2*h+1;d=E(k);d[c]=null;d[h]=a;return new ze(null,e,d)};var Ce=new ze(null,0,[]);function De(a,b,c){this.o=a;this.g=b;this.b=c}
f=De.prototype;f.za=function(a){return a===this.o?this:new De(a,this.g,E(this.b))};f.Na=function(){var a=this.b;return He?He(a):Ie.call(null,a)};f.Aa=function(a,b,c,d){var e=this.b[b>>>a&31];return null!=e?e.Aa(a+5,b,c,d):d};f.Z=function(a,b,c,d,e,g){var h=c>>>b&31,k=this.b[h];if(null==k)return a=ye(this,a,h,Ce.Z(a,b+5,c,d,e,g)),a.g+=1,a;b=k.Z(a,b+5,c,d,e,g);return b===k?this:ye(this,a,h,b)};
f.Y=function(a,b,c,d,e){var g=b>>>a&31,h=this.b[g];if(null==h)return new De(null,this.g+1,xe(this.b,g,Ce.Y(a+5,b,c,d,e)));a=h.Y(a+5,b,c,d,e);return a===h?this:new De(null,this.g,xe(this.b,g,a))};function Je(a,b,c){b*=2;for(var d=0;;)if(d<b){if(we(c,a[d]))return d;d+=2}else return-1}function Ke(a,b,c,d){this.o=a;this.ua=b;this.g=c;this.b=d}f=Ke.prototype;f.za=function(a){if(a===this.o)return this;var b=Array(2*(this.g+1));Ec(this.b,0,b,0,2*this.g);return new Ke(a,this.ua,this.g,b)};
f.Na=function(){var a=this.b;return Ae?Ae(a):Be.call(null,a)};f.Aa=function(a,b,c,d){a=Je(this.b,this.g,c);return 0>a?d:we(c,this.b[a])?this.b[a+1]:d};
f.Z=function(a,b,c,d,e,g){if(c===this.ua){b=Je(this.b,this.g,d);if(-1===b){if(this.b.length>2*this.g)return b=2*this.g,c=2*this.g+1,a=this.za(a),a.b[b]=d,a.b[c]=e,g.ca=!0,a.g+=1,a;c=this.b.length;b=Array(c+2);Ec(this.b,0,b,0,c);b[c]=d;b[c+1]=e;g.ca=!0;d=this.g+1;a===this.o?(this.b=b,this.g=d,a=this):a=new Ke(this.o,this.ua,d,b);return a}return this.b[b+1]===e?this:ye(this,a,b+1,e)}return(new ze(a,1<<(this.ua>>>b&31),[null,this,null,null])).Z(a,b,c,d,e,g)};
f.Y=function(a,b,c,d,e){return b===this.ua?(a=Je(this.b,this.g,c),-1===a?(a=2*this.g,b=Array(a+2),Ec(this.b,0,b,0,a),b[a]=c,b[a+1]=d,e.ca=!0,new Ke(null,this.ua,this.g+1,b)):P.a(this.b[a],d)?this:new Ke(null,this.ua,this.g,xe(this.b,a+1,d))):(new ze(null,1<<(this.ua>>>a&31),[null,this])).Y(a,b,c,d,e)};
function Fe(){switch(arguments.length){case 6:return Ge(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);case 7:return Ee(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}function Ge(a,b,c,d,e,g){var h=Rb(b);if(h===d)return new Ke(null,h,2,[b,c,e,g]);var k=new ve;return Ce.Y(a,h,b,c,k).Y(a,d,e,g,k)}
function Ee(a,b,c,d,e,g,h){var k=Rb(c);if(k===e)return new Ke(null,k,2,[c,d,g,h]);var l=new ve;return Ce.Z(a,b,k,c,d,l).Z(a,b,e,g,h,l)}function Me(a,b,c,d,e){this.l=a;this.wa=b;this.h=c;this.n=d;this.j=e;this.f=32374860;this.m=0}f=Me.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.D=function(){return this.l};f.A=function(){var a=this.j;return null!=a?a:this.j=a=Zb(this)};f.k=function(a,b){return lc(this,b)};f.K=function(a,b){return Ic(b,this)};
f.L=function(a,b,c){return Jc(b,c,this)};f.M=function(){return null==this.n?new X(null,2,5,Y,[this.wa[this.h],this.wa[this.h+1]],null):N(this.n)};f.R=function(){if(null==this.n){var a=this.wa,b=this.h+2;return Ne?Ne(a,b,null):Be.call(null,a,b,null)}var a=this.wa,b=this.h,c=O(this.n);return Ne?Ne(a,b,c):Be.call(null,a,b,c)};f.v=function(){return this};f.I=function(a,b){return new Me(b,this.wa,this.h,this.n,this.j)};f.G=function(a,b){return Q(b,this)};Me.prototype[Ca]=function(){return Xb(this)};
function Be(){switch(arguments.length){case 1:return Ae(arguments[0]);case 3:return Ne(arguments[0],arguments[1],arguments[2]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}function Ae(a){return Ne(a,0,null)}function Ne(a,b,c){if(null==c)for(c=a.length;;)if(b<c){if(null!=a[b])return new Me(null,a,b,null,null);var d=a[b+1];if(v(d)&&(d=d.Na(),v(d)))return new Me(null,a,b+2,d,null);b+=2}else return null;else return new Me(null,a,b,c,null)}
function Oe(a,b,c,d,e){this.l=a;this.wa=b;this.h=c;this.n=d;this.j=e;this.f=32374860;this.m=0}f=Oe.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.D=function(){return this.l};f.A=function(){var a=this.j;return null!=a?a:this.j=a=Zb(this)};f.k=function(a,b){return lc(this,b)};f.K=function(a,b){return Ic(b,this)};f.L=function(a,b,c){return Jc(b,c,this)};f.M=function(){return N(this.n)};
f.R=function(){var a=this.wa,b=this.h,c=O(this.n);return Pe?Pe(null,a,b,c):Ie.call(null,null,a,b,c)};f.v=function(){return this};f.I=function(a,b){return new Oe(b,this.wa,this.h,this.n,this.j)};f.G=function(a,b){return Q(b,this)};Oe.prototype[Ca]=function(){return Xb(this)};function Ie(){switch(arguments.length){case 1:return He(arguments[0]);case 4:return Pe(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error([C("Invalid arity: "),C(arguments.length)].join(""));}}
function He(a){return Pe(null,a,0,null)}function Pe(a,b,c,d){if(null==d)for(d=b.length;;)if(c<d){var e=b[c];if(v(e)&&(e=e.Na(),v(e)))return new Oe(a,b,c+1,e,null);c+=1}else return null;else return new Oe(a,b,c,d,null)}function Qe(a,b,c,d,e,g){this.l=a;this.g=b;this.root=c;this.U=d;this.X=e;this.j=g;this.f=16123663;this.m=8196}f=Qe.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.keys=function(){return Xb(me.d?me.d(this):me.call(null,this))};f.entries=function(){return ie(L(this))};
f.values=function(){return Xb(ne.d?ne.d(this):ne.call(null,this))};f.has=function(a){return tc(this,a,Fc)===Fc?!1:!0};f.get=function(a,b){return this.B(null,a,b)};f.forEach=function(a){for(var b=L(this),c=null,d=0,e=0;;)if(e<d){var g=c.J(null,e),h=R(g,0),g=R(g,1);a.a?a.a(g,h):a.call(null,g,h);e+=1}else if(b=L(b))Cc(b)?(c=zb(b),b=Ab(b),h=c,d=rc(c),c=h):(c=N(b),h=R(c,0),c=g=R(c,1),a.a?a.a(c,h):a.call(null,c,h),b=O(b),c=null,d=0),e=0;else return null};f.u=function(a,b){return I.e(this,b,null)};
f.B=function(a,b,c){return null==b?this.U?this.X:c:null==this.root?c:this.root.Aa(0,Rb(b),b,c)};f.D=function(){return this.l};f.O=function(){return this.g};f.A=function(){var a=this.j;return null!=a?a:this.j=a=ac(this)};f.k=function(a,b){return ge(this,b)};f.Ja=function(){return new Re({},this.root,this.g,this.U,this.X)};
f.aa=function(a,b,c){if(null==b)return this.U&&c===this.X?this:new Qe(this.l,this.U?this.g:this.g+1,this.root,!0,c,null);a=new ve;b=(null==this.root?Ce:this.root).Y(0,Rb(b),b,c,a);return b===this.root?this:new Qe(this.l,a.ca?this.g+1:this.g,b,this.U,this.X,null)};f.v=function(){if(0<this.g){var a=null!=this.root?this.root.Na():null;return this.U?Q(new X(null,2,5,Y,[null,this.X],null),a):a}return null};f.I=function(a,b){return new Qe(b,this.g,this.root,this.U,this.X,this.j)};
f.G=function(a,b){if(Bc(b))return Ua(this,F.a(b,0),F.a(b,1));for(var c=this,d=L(b);;){if(null==d)return c;var e=N(d);if(Bc(e))c=Ua(c,F.a(e,0),F.a(e,1)),d=O(d);else throw Error("conj on a map takes map entries or seqables of map entries");}};
f.call=function(){var a=null,a=function(a,c,d){switch(arguments.length){case 2:return this.u(null,c);case 3:return this.B(null,c,d)}throw Error("Invalid arity: "+arguments.length);};a.a=function(a,c){return this.u(null,c)};a.e=function(a,c,d){return this.B(null,c,d)};return a}();f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.d=function(a){return this.u(null,a)};f.a=function(a,b){return this.B(null,a,b)};var vc=new Qe(null,0,null,!1,null,bc);Qe.prototype[Ca]=function(){return Xb(this)};
function Re(a,b,c,d,e){this.o=a;this.root=b;this.count=c;this.U=d;this.X=e;this.f=258;this.m=56}function Se(a,b){if(a.o){if(b?b.f&2048||b.sb||(b.f?0:z(Wa,b)):z(Wa,b))return Te(a,se.d?se.d(b):se.call(null,b),te.d?te.d(b):te.call(null,b));for(var c=L(b),d=a;;){var e=N(c);if(v(e))var g=e,c=O(c),d=Te(d,function(){var a=g;return se.d?se.d(a):se.call(null,a)}(),function(){var a=g;return te.d?te.d(a):te.call(null,a)}());else return d}}else throw Error("conj! after persistent");}
function Te(a,b,c){if(a.o){if(null==b)a.X!==c&&(a.X=c),a.U||(a.count+=1,a.U=!0);else{var d=new ve;b=(null==a.root?Ce:a.root).Z(a.o,0,Rb(b),b,c,d);b!==a.root&&(a.root=b);d.ca&&(a.count+=1)}return a}throw Error("assoc! after persistent!");}f=Re.prototype;f.O=function(){if(this.o)return this.count;throw Error("count after persistent!");};f.u=function(a,b){return null==b?this.U?this.X:null:null==this.root?null:this.root.Aa(0,Rb(b),b)};
f.B=function(a,b,c){return null==b?this.U?this.X:c:null==this.root?c:this.root.Aa(0,Rb(b),b,c)};f.Ta=function(a,b){return Se(this,b)};f.Ua=function(){var a;if(this.o)this.o=null,a=new Qe(null,this.count,this.root,this.U,this.X,null);else throw Error("persistent! called twice");return a};f.Ka=function(a,b,c){return Te(this,b,c)};var xd=function xd(){return xd.i(0<arguments.length?new M(Array.prototype.slice.call(arguments,0),0):null)};
xd.i=function(a){for(var b=L(a),c=tb(vc);;)if(b){a=O(O(b));var d=N(b),b=N(O(b)),c=wb(c,d,b),b=a}else return vb(c)};xd.t=0;xd.s=function(a){return xd.i(L(a))};function Ue(a,b){this.N=a;this.S=b;this.f=32374988;this.m=0}f=Ue.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.D=function(){return this.S};f.Q=function(){var a=this.N,a=(a?a.f&128||a.Ra||(a.f?0:z(Sa,a)):z(Sa,a))?this.N.Q(null):O(this.N);return null==a?null:new Ue(a,this.S)};f.A=function(){return Zb(this)};
f.k=function(a,b){return lc(this,b)};f.K=function(a,b){return Ic(b,this)};f.L=function(a,b,c){return Jc(b,c,this)};f.M=function(){return this.N.M(null).ab()};f.R=function(){var a=this.N,a=(a?a.f&128||a.Ra||(a.f?0:z(Sa,a)):z(Sa,a))?this.N.Q(null):O(this.N);return null!=a?new Ue(a,this.S):Vb};f.v=function(){return this};f.I=function(a,b){return new Ue(this.N,b)};f.G=function(a,b){return Q(b,this)};Ue.prototype[Ca]=function(){return Xb(this)};function me(a){return(a=L(a))?new Ue(a,null):null}
function se(a){return Xa(a)}function Ve(a,b){this.N=a;this.S=b;this.f=32374988;this.m=0}f=Ve.prototype;f.toString=function(){return Hb(this)};f.equiv=function(a){return this.k(null,a)};f.D=function(){return this.S};f.Q=function(){var a=this.N,a=(a?a.f&128||a.Ra||(a.f?0:z(Sa,a)):z(Sa,a))?this.N.Q(null):O(this.N);return null==a?null:new Ve(a,this.S)};f.A=function(){return Zb(this)};f.k=function(a,b){return lc(this,b)};f.K=function(a,b){return Ic(b,this)};f.L=function(a,b,c){return Jc(b,c,this)};
f.M=function(){return this.N.M(null).bb()};f.R=function(){var a=this.N,a=(a?a.f&128||a.Ra||(a.f?0:z(Sa,a)):z(Sa,a))?this.N.Q(null):O(this.N);return null!=a?new Ve(a,this.S):Vb};f.v=function(){return this};f.I=function(a,b){return new Ve(this.N,b)};f.G=function(a,b){return Q(b,this)};Ve.prototype[Ca]=function(){return Xb(this)};function ne(a){return(a=L(a))?new Ve(a,null):null}function te(a){return Za(a)}
var We=function We(){return We.i(0<arguments.length?new M(Array.prototype.slice.call(arguments,0),0):null)};We.i=function(a){return v(sd(a))?Kc(function(a,c){return oc.a(v(a)?a:qe,c)},a):null};We.t=0;We.s=function(a){return We.i(L(a))};function Zc(a){if(a&&(a.m&4096||a.ub))return a.name;if("string"===typeof a)return a;throw Error([C("Doesn't support name: "),C(a)].join(""));}
function Xe(a,b,c,d,e,g,h){var k=pa;pa=null==pa?null:pa-1;try{if(null!=pa&&0>pa)return J(a,"#");J(a,c);if(0===za.d(g))L(h)&&J(a,function(){var a=Ye.d(g);return v(a)?a:"..."}());else{if(L(h)){var l=N(h);b.e?b.e(l,a,g):b.call(null,l,a,g)}for(var m=O(h),n=za.d(g)-1;;)if(!m||null!=n&&0===n){L(m)&&0===n&&(J(a,d),J(a,function(){var a=Ye.d(g);return v(a)?a:"..."}()));break}else{J(a,d);var p=N(m);c=a;h=g;b.e?b.e(p,c,h):b.call(null,p,c,h);var r=O(m);c=n-1;m=r;n=c}}return J(a,e)}finally{pa=k}}
function Ze(a,b){for(var c=L(b),d=null,e=0,g=0;;)if(g<e){var h=d.J(null,g);J(a,h);g+=1}else if(c=L(c))d=c,Cc(d)?(c=zb(d),e=Ab(d),d=c,h=rc(c),c=e,e=h):(h=N(d),J(a,h),c=O(d),d=null,e=0),g=0;else return null}var $e={'"':'\\"',"\\":"\\\\","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t"};function af(a){return[C('"'),C(a.replace(RegExp('[\\\\"\b\f\n\r\t]',"g"),function(a){return $e[a]})),C('"')].join("")}
function bf(a,b,c){if(null==a)return J(b,"nil");if(void 0===a)return J(b,"#\x3cundefined\x3e");if(v(function(){var b=S(c,wa);return v(b)?(b=a?a.f&131072||a.tb?!0:a.f?!1:z(cb,a):z(cb,a))?zc(a):b:b}())){J(b,"^");var d=zc(a);Z.e?Z.e(d,b,c):Z.call(null,d,b,c);J(b," ")}return null==a?J(b,"nil"):a.Cb?a.Nb(a,b,c):a&&(a.f&2147483648||a.H)?a.r(null,b,c):(null==a?null:a.constructor)===Boolean||"number"===typeof a?J(b,""+C(a)):null!=a&&a.constructor===Object?(J(b,"#js "),d=V.a(function(b){return new X(null,
2,5,Y,[Yc.d(b),a[b]],null)},Dc(a)),cf.p?cf.p(d,Z,b,c):cf.call(null,d,Z,b,c)):Aa(a)?Xe(b,Z,"#js ["," ","]",c,a):v("string"==typeof a)?v(va.d(c))?J(b,af(a)):J(b,a):wc(a)?Ze(b,nc(["#\x3c",""+C(a),"\x3e"],0)):a instanceof Date?(d=function(a,b){for(var c=""+C(a);;)if(rc(c)<b)c=[C("0"),C(c)].join("");else return c},Ze(b,nc(['#inst "',""+C(a.getUTCFullYear()),"-",d(a.getUTCMonth()+1,2),"-",d(a.getUTCDate(),2),"T",d(a.getUTCHours(),2),":",d(a.getUTCMinutes(),2),":",d(a.getUTCSeconds(),2),".",d(a.getUTCMilliseconds(),
3),"-",'00:00"'],0))):v(a instanceof RegExp)?Ze(b,nc(['#"',a.source,'"'],0)):(a?a.f&2147483648||a.H||(a.f?0:z(pb,a)):z(pb,a))?rb(a,b,c):Ze(b,nc(["#\x3c",""+C(a),"\x3e"],0))}function Z(a,b,c){var d=df.d(c);return v(d)?(c=uc.e(c,ef,bf),d.e?d.e(a,b,c):d.call(null,a,b,c)):bf(a,b,c)}
function ff(a){var b=ra(),c;(c=null==a)||(c=L(a),c=v(c)?!1:!0);if(c)b="";else{c=C;var d=new ja;a:{var e=new Gb(d);Z(N(a),e,b);a=L(O(a));for(var g=null,h=0,k=0;;)if(k<h){var l=g.J(null,k);J(e," ");Z(l,e,b);k+=1}else if(a=L(a))g=a,Cc(g)?(a=zb(g),h=Ab(g),g=a,l=rc(a),a=h,h=l):(l=N(g),J(e," "),Z(l,e,b),a=O(g),g=null,h=0),k=0;else break a}b=""+c(d)}return b}function Ad(){return ff(0<arguments.length?new M(Array.prototype.slice.call(arguments,0),0):null)}
function cf(a,b,c,d){return Xe(c,function(a,c,d){var k=Xa(a);b.e?b.e(k,c,d):b.call(null,k,c,d);J(c," ");a=Za(a);return b.e?b.e(a,c,d):b.call(null,a,c,d)},"{",", ","}",d,L(a))}M.prototype.H=!0;M.prototype.r=function(a,b,c){return Xe(b,Z,"("," ",")",c,this)};ad.prototype.H=!0;ad.prototype.r=function(a,b,c){return Xe(b,Z,"("," ",")",c,this)};Me.prototype.H=!0;Me.prototype.r=function(a,b,c){return Xe(b,Z,"("," ",")",c,this)};ke.prototype.H=!0;
ke.prototype.r=function(a,b,c){return Xe(b,Z,"("," ",")",c,this)};Xd.prototype.H=!0;Xd.prototype.r=function(a,b,c){return Xe(b,Z,"("," ",")",c,this)};Wc.prototype.H=!0;Wc.prototype.r=function(a,b,c){return Xe(b,Z,"("," ",")",c,this)};Qe.prototype.H=!0;Qe.prototype.r=function(a,b,c){return cf(this,Z,b,c)};Oe.prototype.H=!0;Oe.prototype.r=function(a,b,c){return Xe(b,Z,"("," ",")",c,this)};ae.prototype.H=!0;ae.prototype.r=function(a,b,c){return Xe(b,Z,"["," ","]",c,this)};ed.prototype.H=!0;
ed.prototype.r=function(a,b,c){return Xe(b,Z,"("," ",")",c,this)};ud.prototype.H=!0;ud.prototype.r=function(a,b,c){J(b,"#\x3cAtom: ");Z(this.state,b,c);return J(b,"\x3e")};Ve.prototype.H=!0;Ve.prototype.r=function(a,b,c){return Xe(b,Z,"("," ",")",c,this)};X.prototype.H=!0;X.prototype.r=function(a,b,c){return Xe(b,Z,"["," ","]",c,this)};Uc.prototype.H=!0;Uc.prototype.r=function(a,b){return J(b,"()")};u.prototype.H=!0;u.prototype.r=function(a,b,c){return cf(this,Z,b,c)};Ue.prototype.H=!0;
Ue.prototype.r=function(a,b,c){return Xe(b,Z,"("," ",")",c,this)};Tc.prototype.H=!0;Tc.prototype.r=function(a,b,c){return Xe(b,Z,"("," ",")",c,this)};var gf=new U(null,"y","y",-1757859776),hf=new U(null,"children","children",-940561982),jf=new U(null,"pump","pump",-453885150),kf=new U(null,"inside","inside",1972503011),wa=new U(null,"meta","meta",1499536964),ya=new U(null,"dup","dup",556298533),lf=new U(null,"key","key",-1516042587),mf=new U(null,"game","game",-441523833),nf=new U(null,"_","_",1453416199),yd=new U(null,"validator","validator",-1966190681),of=new U(null,"width","width",-384071477),pf=new U(null,"type","type",1174270348),ef=new U(null,
"fallback-impl","fallback-impl",-1501286995),ua=new U(null,"flush-on-newline","flush-on-newline",-151457939),qf=new U(null,"field-keys","field-keys",662047758),rf=new U(null,"canvas","canvas",-1798817489),sf=new U(null,"mapstructor","mapstructor",-704323568),va=new U(null,"readably","readably",1129599760),Ye=new U(null,"more-marker","more-marker",-14717935),za=new U(null,"print-length","print-length",1931866356),tf=new U(null,"col","col",-1959363084),uf=new U(null,"right","right",-452581833),vf=new U(null,
"position","position",-2011731912),wf=new U(null,"x","x",2099068185),xf=new U(null,"tag","tag",-1290361223),yf=new U(null,"above","above",-1286866470),zf=new U(null,"speak","speak",-785512965),df=new U(null,"alt-impl","alt-impl",670969595),Af=new U(null,"below","below",-926774883),Bf=new U(null,"outside","outside",-13164995),Cf=new U(null,"message","message",-406056002),Df=new U(null,"height","height",1025178622),Ef=new U(null,"left","left",-399115937);if("undefined"===typeof Ff)var Ff=wd?wd(0):vd.call(null,0);
var Gf=wd?wd(qe):vd.call(null,qe),Hf=function Hf(b){if(b?b.Ma:b)return b.Ma(b);var c;c=Hf[q(null==b?null:b)];if(!c&&(c=Hf._,!c))throw B("IComponent.-keyword",b);return c.call(null,b)},Jf=function Jf(b){if(b?b.Ea:b)return b.Ea(b);var c;c=Jf[q(null==b?null:b)];if(!c&&(c=Jf._,!c))throw B("IPass.init",b);return c.call(null,b)},Kf=function Kf(b){if(b?b.Fa:b)return b.Fa(b);var c;c=Kf[q(null==b?null:b)];if(!c&&(c=Kf._,!c))throw B("IPass.update",b);return c.call(null,b)},Lf=function Lf(b){if(b?b.Da:b)return b.Da(b);
var c;c=Lf[q(null==b?null:b)];if(!c&&(c=Lf._,!c))throw B("IPass.draw",b);return c.call(null,b)},Mf=function Mf(b){if(b?b.Ca:b)return b.Ca(b);var c;c=Mf[q(null==b?null:b)];if(!c&&(c=Mf._,!c))throw B("IPass.clone",b);return c.call(null,b)};function Nf(a,b,c){this.uid=a;this.Va=b;this.data=c;this.f=2155874048;this.m=0}f=Nf.prototype;f.r=function(a,b){return J(b,[C("\x3cE"),C(this.uid),C("\x3e")].join(""))};f.v=function(){var a;a=this.data;a=dc.d?dc.d(a):dc.call(null,a);return L(a)};
f.u=function(a,b){var c;c=this.data;c=dc.d?dc.d(c):dc.call(null,c);return S(c,b)};f.aa=function(a,b,c){a=this.uid;var d=this.Va,e;e=this.data;e=dc.d?dc.d(e):dc.call(null,e);return new Nf(a,d,Ua(e,b,c))};f.Ea=function(){return this.Va.every(function(){return function(a){Jf(a);return!0}}(this))};f.Fa=function(){return this.Va.every(function(){return function(a){Kf(a);return!0}}(this))};f.Da=function(){return this.Va.every(function(){return function(a){Lf(a);return!0}}(this))};f.Ca=function(){return this};
function Of(a){var b=R(a,0);a=R(a,1);var c=S(dc.d?dc.d(Gf):dc.call(null,Gf),b);return v(c)?(c=Gc(c)?nd(xd,c):c,S(c,pf),c=S(c,sf),new re([b,c.d?c.d(a):c.call(null,a)])):qe}function Pf(a,b){var c=Mf(a);c.parent=b;return Bd.e(b.data,oc,new re([Hf(a),c]))};var Qf;a:{var Rf=aa.navigator;if(Rf){var Sf=Rf.userAgent;if(Sf){Qf=Sf;break a}}Qf=""};var Tf=-1!=Qf.indexOf("Opera")||-1!=Qf.indexOf("OPR"),Uf=-1!=Qf.indexOf("Trident")||-1!=Qf.indexOf("MSIE"),Vf=-1!=Qf.indexOf("Gecko")&&-1==Qf.toLowerCase().indexOf("webkit")&&!(-1!=Qf.indexOf("Trident")||-1!=Qf.indexOf("MSIE")),Wf=-1!=Qf.toLowerCase().indexOf("webkit"),Xf=function(){var a="",b;if(Tf&&aa.opera)return a=aa.opera.version,"function"==q(a)?a():a;Vf?b=/rv\:([^\);]+)(\)|;)/:Uf?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Wf&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(Qf))?a[1]:"");return Uf&&(b=(b=aa.document)?
b.documentMode:void 0,b>parseFloat(a))?String(b):a}(),Yf={};
function Zf(a){var b;if(!(b=Yf[a])){b=0;for(var c=String(Xf).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=Math.max(c.length,d.length),g=0;0==b&&g<e;g++){var h=c[g]||"",k=d[g]||"",l=RegExp("(\\d*)(\\D*)","g"),m=RegExp("(\\d*)(\\D*)","g");do{var n=l.exec(h)||["","",""],p=m.exec(k)||["","",""];if(0==n[0].length&&0==p[0].length)break;b=ga(0==n[1].length?0:parseInt(n[1],10),0==p[1].length?0:parseInt(p[1],10))||ga(0==n[2].length,0==p[2].length)||
ga(n[2],p[2])}while(0==b)}b=Yf[a]=0<=b}return b};Uf&&Zf("9");!Wf||Zf("528");Vf&&Zf("1.9b")||Uf&&Zf("8")||Tf&&Zf("9.5")||Wf&&Zf("528");Vf&&!Zf("8")||Uf&&Zf("9");function $f(a){return window.requestAnimationFrame(a)}function ag(a,b){this.parent=a;this.kb=b;this.f=2155873025;this.m=0}f=ag.prototype;f.r=function(a,b){return J(b,[C("\x3c"),C("pump"),C(ne(this)),C("\x3e")].join(""))};f.v=function(){return V.a(function(a){return function(b){var c=R(b,0);b=R(b,1);return new X(null,2,5,Y,[c,a[b]],null)}}(this),new u(null,1,[nf,"_"],null))};f.u=function(a,b){return this[S(new u(null,1,[nf,"_"],null),b)]};
f.aa=function(a,b,c){return this[S(new u(null,1,[nf,"_"],null),b)]=c};f.Ma=function(){return jf};f.call=function(a,b){return Pf(this,b)};f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.d=function(a){return Pf(this,a)};f.Ca=function(){return new ag(this.parent,this.kb)};f.Ea=function(){return null};f.Fa=function(){Lf(this.parent);return $f(function(a){return function(){return Kf(a.parent)}}(this))};f.Da=function(){return null};
Bd.i(Gf,W,new X(null,1,5,Y,[jf],null),We,nc([new u(null,3,[pf,ag,qf,new X(null,1,5,Y,[nf],null),sf,function(a){a=Gc(a)?nd(xd,a):a;a=S(a,nf);return new ag(null,a)}],null)],0));var bg=wd?wd(qe):vd.call(null,qe);function cg(a,b){this.parent=a;this.key=b;this.f=2155873025;this.m=0}f=cg.prototype;f.r=function(a,b){return J(b,[C("\x3c"),C("tag"),C(ne(this)),C("\x3e")].join(""))};
f.v=function(){return V.a(function(a){return function(b){var c=R(b,0);b=R(b,1);return new X(null,2,5,Y,[c,a[b]],null)}}(this),new u(null,1,[lf,"key"],null))};f.u=function(a,b){return this[S(new u(null,1,[lf,"key"],null),b)]};f.aa=function(a,b,c){return this[S(new u(null,1,[lf,"key"],null),b)]=c};f.Ma=function(){return xf};f.call=function(a,b){return Pf(this,b)};f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.d=function(a){return Pf(this,a)};
f.Ca=function(){return new cg(this.parent,this.key)};f.Ea=function(){return Bd.i(bg,W,new X(null,1,5,Y,[this.key],null),oc,nc([this.parent],0))};f.Fa=function(){return null};f.Da=function(){return null};Bd.i(Gf,W,new X(null,1,5,Y,[xf],null),We,nc([new u(null,3,[pf,cg,qf,new X(null,1,5,Y,[lf],null),sf,function(a){a=Gc(a)?nd(xd,a):a;a=S(a,lf);return new cg(null,a)}],null)],0));function dg(a,b){this.parent=a;this.La=b;this.f=2155873025;this.m=0}f=dg.prototype;
f.r=function(a,b){return J(b,[C("\x3c"),C("children"),C(ne(this)),C("\x3e")].join(""))};f.v=function(){return V.a(function(a){return function(b){var c=R(b,0);b=R(b,1);return new X(null,2,5,Y,[c,a[b]],null)}}(this),new u(null,1,[tf,"col"],null))};f.u=function(a,b){return this[S(new u(null,1,[tf,"col"],null),b)]};f.aa=function(a,b,c){return this[S(new u(null,1,[tf,"col"],null),b)]=c};f.Ma=function(){return hf};f.call=function(a,b){return Pf(this,b)};
f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.d=function(a){return Pf(this,a)};f.Ca=function(){return new dg(this.parent,this.La)};f.Ea=function(){uc.e(this,tf,hd(this.La));return this.La.every(function(){return function(a){Jf(a);return!0}}(this))};f.Fa=function(){return this.La.every(function(){return function(a){Kf(a);return!0}}(this))};f.Da=function(){return this.La.every(function(){return function(a){Lf(a);return!0}}(this))};
Bd.i(Gf,W,new X(null,1,5,Y,[hf],null),We,nc([new u(null,3,[pf,dg,qf,new X(null,1,5,Y,[tf],null),sf,function(a){a=Gc(a)?nd(xd,a):a;a=S(a,tf);return new dg(null,a)}],null)],0));na=!1;ka=function(){function a(a){var d=null;if(0<arguments.length){for(var d=0,e=Array(arguments.length-0);d<e.length;)e[d]=arguments[d+0],++d;d=new M(e,0)}return b.call(this,d)}function b(a){return console.log.apply(console,Ha?Fa(a):Ea.call(null,a))}a.t=0;a.s=function(a){a=L(a);return b(a)};a.i=b;return a}();function eg(a,b){this.parent=a;this.message=b;this.f=2155873025;this.m=0}f=eg.prototype;f.r=function(a,b){return J(b,[C("\x3c"),C("speak"),C(ne(this)),C("\x3e")].join(""))};
f.v=function(){return V.a(function(a){return function(b){var c=R(b,0);b=R(b,1);return new X(null,2,5,Y,[c,a[b]],null)}}(this),new u(null,1,[Cf,"message"],null))};f.u=function(a,b){return this[S(new u(null,1,[Cf,"message"],null),b)]};f.aa=function(a,b,c){return this[S(new u(null,1,[Cf,"message"],null),b)]=c};f.Ma=function(){return zf};f.call=function(a,b){return Pf(this,b)};f.apply=function(a,b){return this.call.apply(this,[this].concat(E(b)))};f.d=function(a){return Pf(this,a)};
f.Ca=function(){return new eg(this.parent,this.message)};f.Ea=function(){var a=nc([this,new Tb(null,"belongs","belongs",-1293196141,null),new Tb(null,"to","to",1832630534,null),this.parent],0),a=ff(a);ka.d?ka.d(a):ka.call(null,a);v(na)?(a=ra(),ka.d?ka.d("\n"):ka.call(null,"\n"),a=(S(a,ua),null)):a=null;return a};f.Fa=function(){return null};f.Da=function(){return null};
Bd.i(Gf,W,new X(null,1,5,Y,[zf],null),We,nc([new u(null,3,[pf,eg,qf,new X(null,1,5,Y,[Cf],null),sf,function(a){a=Gc(a)?nd(xd,a):a;a=S(a,Cf);return new eg(null,a)}],null)],0));
var fg=function(){var a=function(){var a=Fd(qe,Gd(Of,new u(null,5,[vf,new u(null,2,[wf,5,gf,5],null),xf,new u(null,1,[lf,mf],null),jf,qe,rf,new u(null,2,[of,640,Df,480],null),zf,new u(null,1,[Cf,"hello from cljs"],null)],null)));return wd?wd(a):vd.call(null,a)}(),b=Ha(ne(dc.d?dc.d(a):dc.call(null,a))),c=new Nf(Bd.a(Ff,cc),b,a);Gd(function(a,b,c){return function(a){return a.parent=c}}(a,b,c),b);return c}();Jf(fg);Kf(fg);S(dc.d?dc.d(bg):dc.call(null,bg),mf);function gg(a,b,c){c="number"===typeof c?Wd(Cd(rc(b),Dd(c))):Xc(c)?Wd(c):c;return td(function(b){return function(c,g){var h=tc(b,c,0);return a.a?a.a(g,h):a.call(null,g,h)}}(c),b)}function hg(a,b){return Wd(Kc(function(b,d){return gg(a,b,d)},b))}
function ig(a,b){var c=R(a,0),d=R(a,1),e=R(a,2),g=R(a,3),h=R(b,0),k=R(b,1),l=R(b,2),m=R(b,3),h=new X(null,4,5,Y,[h,h,k,k],null),l=nc([new X(null,4,5,Y,[l,-l,m,-m],null),.5],0),l=hg(Oc,l),l=nc([h,l],0),l=hg(Mc,l),c=new X(null,4,5,Y,[c,c,d,d],null),e=nc([new X(null,4,5,Y,[e,-e,g,-g],null),.5],0),e=hg(Oc,e),e=nc([c,e],0),e=hg(Mc,e),e=nc([l,e],0);return hg(Nc,e)}
function jg(a){a=Gd(Rc,a);var b=R(a,0),c=R(a,1),d=R(a,2),e=R(a,3);(function(){var a=new X(null,2,5,Y,[b,c],null);return P.a(new X(null,2,5,Y,[!0,!0],null),a)?kf:P.a(new X(null,2,5,Y,[!1,!1],null),a)?Bf:P.a(new X(null,2,5,Y,[!0,!1],null),a)?uf:P.a(new X(null,2,5,Y,[!1,!0],null),a)?Ef:null})();(function(){var a=new X(null,2,5,Y,[d,e],null);return P.a(new X(null,2,5,Y,[!0,!0],null),a)?kf:P.a(new X(null,2,5,Y,[!1,!1],null),a)?Bf:P.a(new X(null,2,5,Y,[!0,!1],null),a)?yf:P.a(new X(null,2,5,Y,[!1,!0],null),
a)?Af:null})()}jg(ig(new X(null,4,5,Y,[10,20,100,100],null),new X(null,4,5,Y,[70,40,50,50],null)));jg(ig(new X(null,4,5,Y,[0,0,100,100],null),new X(null,4,5,Y,[50,50,10,10],null)));jg(ig(new X(null,4,5,Y,[0,0,100,100],null),new X(null,4,5,Y,[-10,90,20,80],null)));